/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.resources.shares;

import com.apologist.core.ClientOptions;
import com.apologist.core.RequestOptions;
import com.apologist.resources.shares.requests.GetSharedMessagesRequest;
import com.apologist.resources.shares.types.GetSharedMessagesResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncSharesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawSharesClient rawClient;

    public AsyncSharesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawSharesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawSharesClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Public, unauthenticated read of the messages behind a share token. The token is the bearer capability and enforces tenant isolation against the host agent. An empty or invalid token yields an empty messages array.
     */
    public CompletableFuture<GetSharedMessagesResponse> getSharedMessages(String token) {
        return this.rawClient.getSharedMessages(token).thenApply(response -> response.body());
    }

    /**
     * Public, unauthenticated read of the messages behind a share token. The token is the bearer capability and enforces tenant isolation against the host agent. An empty or invalid token yields an empty messages array.
     */
    public CompletableFuture<GetSharedMessagesResponse> getSharedMessages(String token, RequestOptions requestOptions) {
        return this.rawClient.getSharedMessages(token, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Public, unauthenticated read of the messages behind a share token. The token is the bearer capability and enforces tenant isolation against the host agent. An empty or invalid token yields an empty messages array.
     */
    public CompletableFuture<GetSharedMessagesResponse> getSharedMessages(
            String token, GetSharedMessagesRequest request) {
        return this.rawClient.getSharedMessages(token, request).thenApply(response -> response.body());
    }

    /**
     * Public, unauthenticated read of the messages behind a share token. The token is the bearer capability and enforces tenant isolation against the host agent. An empty or invalid token yields an empty messages array.
     */
    public CompletableFuture<GetSharedMessagesResponse> getSharedMessages(
            String token, GetSharedMessagesRequest request, RequestOptions requestOptions) {
        return this.rawClient.getSharedMessages(token, request, requestOptions).thenApply(response -> response.body());
    }
}
