/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.api.resources.channels;

import com.apologist.api.core.ApologistClientApiException;
import com.apologist.api.core.ApologistClientException;
import com.apologist.api.core.ApologistClientHttpResponse;
import com.apologist.api.core.ClientOptions;
import com.apologist.api.core.MediaTypes;
import com.apologist.api.core.ObjectMappers;
import com.apologist.api.core.QueryStringMapper;
import com.apologist.api.core.RequestOptions;
import com.apologist.api.core.RetryInterceptor;
import com.apologist.api.errors.BadRequestError;
import com.apologist.api.errors.ForbiddenError;
import com.apologist.api.errors.InternalServerError;
import com.apologist.api.errors.NotFoundError;
import com.apologist.api.errors.ServiceUnavailableError;
import com.apologist.api.errors.UnauthorizedError;
import com.apologist.api.resources.channels.requests.GetDiscordChannelStatusRequest;
import com.apologist.api.resources.channels.requests.GetInstagramPrivacyPolicyRequest;
import com.apologist.api.resources.channels.requests.ReceiveDiscordInteractionRequest;
import com.apologist.api.resources.channels.requests.ReceiveFacebookMessageRequest;
import com.apologist.api.resources.channels.requests.ReceiveTelegramUpdateRequest;
import com.apologist.api.resources.channels.requests.ReceiveTwilioMessageRequest;
import com.apologist.api.resources.channels.requests.VerifyFacebookWebhookRequest;
import com.apologist.api.resources.channels.types.GetDiscordChannelStatusResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import okhttp3.FormBody;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawChannelsClient {
    protected final ClientOptions clientOptions;

    public RawChannelsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns the status of the Discord channel. Used as a lightweight health/verification endpoint.
     */
    public ApologistClientHttpResponse<GetDiscordChannelStatusResponse> getDiscordChannelStatus(String id) {
        return getDiscordChannelStatus(
                id, GetDiscordChannelStatusRequest.builder().build());
    }

    /**
     * Returns the status of the Discord channel. Used as a lightweight health/verification endpoint.
     */
    public ApologistClientHttpResponse<GetDiscordChannelStatusResponse> getDiscordChannelStatus(
            String id, RequestOptions requestOptions) {
        return getDiscordChannelStatus(
                id, GetDiscordChannelStatusRequest.builder().build(), requestOptions);
    }

    /**
     * Returns the status of the Discord channel. Used as a lightweight health/verification endpoint.
     */
    public ApologistClientHttpResponse<GetDiscordChannelStatusResponse> getDiscordChannelStatus(
            String id, GetDiscordChannelStatusRequest request) {
        return getDiscordChannelStatus(id, request, null);
    }

    /**
     * Returns the status of the Discord channel. Used as a lightweight health/verification endpoint.
     */
    public ApologistClientHttpResponse<GetDiscordChannelStatusResponse> getDiscordChannelStatus(
            String id, GetDiscordChannelStatusRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("channels")
                .addPathSegment(id)
                .addPathSegments("discord");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ApologistClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetDiscordChannelStatusResponse.class),
                        response);
            }
            try {
                if (response.code() == 404) {
                    throw new NotFoundError(
                            ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApologistClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new ApologistClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new ApologistClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Receives Discord interaction callbacks for the channel. Requests are verified via Ed25519 signature headers; unsigned or invalid requests are rejected. Payload shape is defined by Discord.
     */
    public ApologistClientHttpResponse<Void> receiveDiscordInteraction(
            String id, ReceiveDiscordInteractionRequest request) {
        return receiveDiscordInteraction(id, request, null);
    }

    /**
     * Receives Discord interaction callbacks for the channel. Requests are verified via Ed25519 signature headers; unsigned or invalid requests are rejected. Payload shape is defined by Discord.
     */
    public ApologistClientHttpResponse<Void> receiveDiscordInteraction(
            String id, ReceiveDiscordInteractionRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("channels")
                .addPathSegment(id)
                .addPathSegments("discord");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json");
        _requestBuilder.addHeader("x-signature-ed25519", request.getSignatureEd25519());
        _requestBuilder.addHeader("x-signature-timestamp", request.getSignatureTimestamp());
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new ApologistClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApologistClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new ApologistClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new ApologistClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Handles the Meta webhook verification handshake, echoing <code>hub.challenge</code> when <code>hub.verify_token</code> matches the channel's configured token.
     */
    public ApologistClientHttpResponse<String> verifyFacebookWebhook(String id, VerifyFacebookWebhookRequest request) {
        return verifyFacebookWebhook(id, request, null);
    }

    /**
     * Handles the Meta webhook verification handshake, echoing <code>hub.challenge</code> when <code>hub.verify_token</code> matches the channel's configured token.
     */
    public ApologistClientHttpResponse<String> verifyFacebookWebhook(
            String id, VerifyFacebookWebhookRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("channels")
                .addPathSegment(id)
                .addPathSegments("facebook");
        QueryStringMapper.addQueryParameter(httpUrl, "hub.mode", request.getHubMode(), false);
        QueryStringMapper.addQueryParameter(httpUrl, "hub.verify_token", request.getHubVerifyToken(), false);
        if (request.getHubChallenge().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "hub.challenge", request.getHubChallenge().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ApologistClientHttpResponse<>(responseBodyString, response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApologistClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new ApologistClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new ApologistClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Receives Facebook/Messenger (and Instagram-style) message events for the channel. Payload shape is defined by Meta.
     */
    public ApologistClientHttpResponse<Void> receiveFacebookMessage(String id, ReceiveFacebookMessageRequest request) {
        return receiveFacebookMessage(id, request, null);
    }

    /**
     * Receives Facebook/Messenger (and Instagram-style) message events for the channel. Payload shape is defined by Meta.
     */
    public ApologistClientHttpResponse<Void> receiveFacebookMessage(
            String id, ReceiveFacebookMessageRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("channels")
                .addPathSegment(id)
                .addPathSegments("facebook");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ApologistClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new ApologistClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 503:
                        throw new ServiceUnavailableError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApologistClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new ApologistClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new ApologistClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns a static HTML privacy policy page for the Instagram integration.
     */
    public ApologistClientHttpResponse<String> getInstagramPrivacyPolicy(String id) {
        return getInstagramPrivacyPolicy(
                id, GetInstagramPrivacyPolicyRequest.builder().build());
    }

    /**
     * Returns a static HTML privacy policy page for the Instagram integration.
     */
    public ApologistClientHttpResponse<String> getInstagramPrivacyPolicy(String id, RequestOptions requestOptions) {
        return getInstagramPrivacyPolicy(
                id, GetInstagramPrivacyPolicyRequest.builder().build(), requestOptions);
    }

    /**
     * Returns a static HTML privacy policy page for the Instagram integration.
     */
    public ApologistClientHttpResponse<String> getInstagramPrivacyPolicy(
            String id, GetInstagramPrivacyPolicyRequest request) {
        return getInstagramPrivacyPolicy(id, request, null);
    }

    /**
     * Returns a static HTML privacy policy page for the Instagram integration.
     */
    public ApologistClientHttpResponse<String> getInstagramPrivacyPolicy(
            String id, GetInstagramPrivacyPolicyRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("channels")
                .addPathSegment(id)
                .addPathSegments("instagram")
                .addPathSegments("privacy");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)));
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ApologistClientHttpResponse<>(responseBodyString, response);
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApologistClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new ApologistClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new ApologistClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Receives Telegram bot update events for the channel. Non-message updates are acknowledged and ignored. Payload shape is defined by Telegram.
     */
    public ApologistClientHttpResponse<Void> receiveTelegramUpdate(String id, ReceiveTelegramUpdateRequest request) {
        return receiveTelegramUpdate(id, request, null);
    }

    /**
     * Receives Telegram bot update events for the channel. Non-message updates are acknowledged and ignored. Payload shape is defined by Telegram.
     */
    public ApologistClientHttpResponse<Void> receiveTelegramUpdate(
            String id, ReceiveTelegramUpdateRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("channels")
                .addPathSegment(id)
                .addPathSegments("telegram");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request.getBody()), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ApologistClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new ApologistClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApologistClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new ApologistClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new ApologistClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Receives inbound Twilio messages for the channel as form-encoded data. Payload fields are defined by Twilio.
     */
    public ApologistClientHttpResponse<Void> receiveTwilioMessage(String id) {
        return receiveTwilioMessage(id, ReceiveTwilioMessageRequest.builder().build());
    }

    /**
     * Receives inbound Twilio messages for the channel as form-encoded data. Payload fields are defined by Twilio.
     */
    public ApologistClientHttpResponse<Void> receiveTwilioMessage(String id, RequestOptions requestOptions) {
        return receiveTwilioMessage(id, ReceiveTwilioMessageRequest.builder().build(), requestOptions);
    }

    /**
     * Receives inbound Twilio messages for the channel as form-encoded data. Payload fields are defined by Twilio.
     */
    public ApologistClientHttpResponse<Void> receiveTwilioMessage(String id, ReceiveTwilioMessageRequest request) {
        return receiveTwilioMessage(id, request, null);
    }

    /**
     * Receives inbound Twilio messages for the channel as form-encoded data. Payload fields are defined by Twilio.
     */
    public ApologistClientHttpResponse<Void> receiveTwilioMessage(
            String id, ReceiveTwilioMessageRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("channels")
                .addPathSegment(id)
                .addPathSegments("twilio");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        FormBody.Builder body = new FormBody.Builder();
        try {
            if (request.getFrom().isPresent()) {
                body.add("From", String.valueOf(request.getFrom().get()));
            }
            if (request.getBody().isPresent()) {
                body.add("Body", String.valueOf(request.getBody().get()));
            }
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body.build())
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/x-www-form-urlencoded")
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return new ApologistClientHttpResponse<>(null, response);
            }
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApologistClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new ApologistClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new ApologistClientException("Network error executing HTTP request", e);
        }
    }
}
