/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.ai.api.resources.ctas;

import com.apologist.ai.api.core.ApologistAiApiApiException;
import com.apologist.ai.api.core.ApologistAiApiException;
import com.apologist.ai.api.core.ApologistAiApiHttpResponse;
import com.apologist.ai.api.core.ClientOptions;
import com.apologist.ai.api.core.MediaTypes;
import com.apologist.ai.api.core.ObjectMappers;
import com.apologist.ai.api.core.RequestOptions;
import com.apologist.ai.api.core.RetryInterceptor;
import com.apologist.ai.api.errors.ForbiddenError;
import com.apologist.ai.api.errors.InternalServerError;
import com.apologist.ai.api.errors.ServiceUnavailableError;
import com.apologist.ai.api.errors.UnprocessableEntityError;
import com.apologist.ai.api.resources.ctas.requests.CtaClickRequest;
import com.apologist.ai.api.resources.ctas.types.MatchCtasResponse;
import com.apologist.ai.api.types.CtaMatchRequest;
import com.apologist.ai.api.types.Error;
import com.apologist.ai.api.types.SuccessResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawCtAsClient {
    protected final ClientOptions clientOptions;

    public AsyncRawCtAsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Finds matching CTAs based on conversation context, user, session, device, or messages
     */
    public CompletableFuture<ApologistAiApiHttpResponse<MatchCtasResponse>> matchCtas(CtaMatchRequest request) {
        return matchCtas(request, null);
    }

    /**
     * Finds matching CTAs based on conversation context, user, session, device, or messages
     */
    public CompletableFuture<ApologistAiApiHttpResponse<MatchCtasResponse>> matchCtas(
            CtaMatchRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("ctas/match");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ApologistAiApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<ApologistAiApiHttpResponse<MatchCtasResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new ApologistAiApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, MatchCtasResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 503:
                                future.completeExceptionally(new ServiceUnavailableError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new ApologistAiApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new ApologistAiApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(
                            new ApologistAiApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new ApologistAiApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Records that a user clicked on a specific CTA
     */
    public CompletableFuture<ApologistAiApiHttpResponse<SuccessResponse>> logCtaClick(
            String id, CtaClickRequest request) {
        return logCtaClick(id, request, null);
    }

    /**
     * Records that a user clicked on a specific CTA
     */
    public CompletableFuture<ApologistAiApiHttpResponse<SuccessResponse>> logCtaClick(
            String id, CtaClickRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("ctas")
                .addPathSegment(id)
                .addPathSegments("click");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ApologistAiApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<ApologistAiApiHttpResponse<SuccessResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new ApologistAiApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SuccessResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 503:
                                future.completeExceptionally(new ServiceUnavailableError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new ApologistAiApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new ApologistAiApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(
                            new ApologistAiApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new ApologistAiApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
