/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.resources.evaluators.requests;

import ai.apologist.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListEvaluationsRequest.Builder.class)
public final class ListEvaluationsRequest {
    private final Optional<Integer> page;

    private final Optional<Integer> perPage;

    private final Optional<String> minTimestamp;

    private final Optional<String> maxTimestamp;

    private final Optional<String> minDuration;

    private final Optional<String> maxDuration;

    private final Optional<String> minScore;

    private final Optional<String> maxScore;

    private final Optional<String> passed;

    private final Optional<String> benchmark;

    private final Optional<String> benchmarkRunId;

    private final Optional<String> benchmarkQuestionId;

    private final Map<String, Object> additionalProperties;

    private ListEvaluationsRequest(
            Optional<Integer> page,
            Optional<Integer> perPage,
            Optional<String> minTimestamp,
            Optional<String> maxTimestamp,
            Optional<String> minDuration,
            Optional<String> maxDuration,
            Optional<String> minScore,
            Optional<String> maxScore,
            Optional<String> passed,
            Optional<String> benchmark,
            Optional<String> benchmarkRunId,
            Optional<String> benchmarkQuestionId,
            Map<String, Object> additionalProperties) {
        this.page = page;
        this.perPage = perPage;
        this.minTimestamp = minTimestamp;
        this.maxTimestamp = maxTimestamp;
        this.minDuration = minDuration;
        this.maxDuration = maxDuration;
        this.minScore = minScore;
        this.maxScore = maxScore;
        this.passed = passed;
        this.benchmark = benchmark;
        this.benchmarkRunId = benchmarkRunId;
        this.benchmarkQuestionId = benchmarkQuestionId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("page")
    public Optional<Integer> getPage() {
        return page;
    }

    /**
     * @return Results per page (clamped to 100).
     */
    @JsonProperty("per_page")
    public Optional<Integer> getPerPage() {
        return perPage;
    }

    @JsonProperty("min_timestamp")
    public Optional<String> getMinTimestamp() {
        return minTimestamp;
    }

    @JsonProperty("max_timestamp")
    public Optional<String> getMaxTimestamp() {
        return maxTimestamp;
    }

    @JsonProperty("min_duration")
    public Optional<String> getMinDuration() {
        return minDuration;
    }

    @JsonProperty("max_duration")
    public Optional<String> getMaxDuration() {
        return maxDuration;
    }

    @JsonProperty("min_score")
    public Optional<String> getMinScore() {
        return minScore;
    }

    @JsonProperty("max_score")
    public Optional<String> getMaxScore() {
        return maxScore;
    }

    @JsonProperty("passed")
    public Optional<String> getPassed() {
        return passed;
    }

    @JsonProperty("benchmark")
    public Optional<String> getBenchmark() {
        return benchmark;
    }

    @JsonProperty("benchmark_run_id")
    public Optional<String> getBenchmarkRunId() {
        return benchmarkRunId;
    }

    @JsonProperty("benchmark_question_id")
    public Optional<String> getBenchmarkQuestionId() {
        return benchmarkQuestionId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListEvaluationsRequest && equalTo((ListEvaluationsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListEvaluationsRequest other) {
        return page.equals(other.page)
                && perPage.equals(other.perPage)
                && minTimestamp.equals(other.minTimestamp)
                && maxTimestamp.equals(other.maxTimestamp)
                && minDuration.equals(other.minDuration)
                && maxDuration.equals(other.maxDuration)
                && minScore.equals(other.minScore)
                && maxScore.equals(other.maxScore)
                && passed.equals(other.passed)
                && benchmark.equals(other.benchmark)
                && benchmarkRunId.equals(other.benchmarkRunId)
                && benchmarkQuestionId.equals(other.benchmarkQuestionId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.page,
                this.perPage,
                this.minTimestamp,
                this.maxTimestamp,
                this.minDuration,
                this.maxDuration,
                this.minScore,
                this.maxScore,
                this.passed,
                this.benchmark,
                this.benchmarkRunId,
                this.benchmarkQuestionId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> page = Optional.empty();

        private Optional<Integer> perPage = Optional.empty();

        private Optional<String> minTimestamp = Optional.empty();

        private Optional<String> maxTimestamp = Optional.empty();

        private Optional<String> minDuration = Optional.empty();

        private Optional<String> maxDuration = Optional.empty();

        private Optional<String> minScore = Optional.empty();

        private Optional<String> maxScore = Optional.empty();

        private Optional<String> passed = Optional.empty();

        private Optional<String> benchmark = Optional.empty();

        private Optional<String> benchmarkRunId = Optional.empty();

        private Optional<String> benchmarkQuestionId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListEvaluationsRequest other) {
            page(other.getPage());
            perPage(other.getPerPage());
            minTimestamp(other.getMinTimestamp());
            maxTimestamp(other.getMaxTimestamp());
            minDuration(other.getMinDuration());
            maxDuration(other.getMaxDuration());
            minScore(other.getMinScore());
            maxScore(other.getMaxScore());
            passed(other.getPassed());
            benchmark(other.getBenchmark());
            benchmarkRunId(other.getBenchmarkRunId());
            benchmarkQuestionId(other.getBenchmarkQuestionId());
            return this;
        }

        @JsonSetter(value = "page", nulls = Nulls.SKIP)
        public Builder page(Optional<Integer> page) {
            this.page = page;
            return this;
        }

        public Builder page(Integer page) {
            this.page = Optional.ofNullable(page);
            return this;
        }

        /**
         * <p>Results per page (clamped to 100).</p>
         */
        @JsonSetter(value = "per_page", nulls = Nulls.SKIP)
        public Builder perPage(Optional<Integer> perPage) {
            this.perPage = perPage;
            return this;
        }

        public Builder perPage(Integer perPage) {
            this.perPage = Optional.ofNullable(perPage);
            return this;
        }

        @JsonSetter(value = "min_timestamp", nulls = Nulls.SKIP)
        public Builder minTimestamp(Optional<String> minTimestamp) {
            this.minTimestamp = minTimestamp;
            return this;
        }

        public Builder minTimestamp(String minTimestamp) {
            this.minTimestamp = Optional.ofNullable(minTimestamp);
            return this;
        }

        @JsonSetter(value = "max_timestamp", nulls = Nulls.SKIP)
        public Builder maxTimestamp(Optional<String> maxTimestamp) {
            this.maxTimestamp = maxTimestamp;
            return this;
        }

        public Builder maxTimestamp(String maxTimestamp) {
            this.maxTimestamp = Optional.ofNullable(maxTimestamp);
            return this;
        }

        @JsonSetter(value = "min_duration", nulls = Nulls.SKIP)
        public Builder minDuration(Optional<String> minDuration) {
            this.minDuration = minDuration;
            return this;
        }

        public Builder minDuration(String minDuration) {
            this.minDuration = Optional.ofNullable(minDuration);
            return this;
        }

        @JsonSetter(value = "max_duration", nulls = Nulls.SKIP)
        public Builder maxDuration(Optional<String> maxDuration) {
            this.maxDuration = maxDuration;
            return this;
        }

        public Builder maxDuration(String maxDuration) {
            this.maxDuration = Optional.ofNullable(maxDuration);
            return this;
        }

        @JsonSetter(value = "min_score", nulls = Nulls.SKIP)
        public Builder minScore(Optional<String> minScore) {
            this.minScore = minScore;
            return this;
        }

        public Builder minScore(String minScore) {
            this.minScore = Optional.ofNullable(minScore);
            return this;
        }

        @JsonSetter(value = "max_score", nulls = Nulls.SKIP)
        public Builder maxScore(Optional<String> maxScore) {
            this.maxScore = maxScore;
            return this;
        }

        public Builder maxScore(String maxScore) {
            this.maxScore = Optional.ofNullable(maxScore);
            return this;
        }

        @JsonSetter(value = "passed", nulls = Nulls.SKIP)
        public Builder passed(Optional<String> passed) {
            this.passed = passed;
            return this;
        }

        public Builder passed(String passed) {
            this.passed = Optional.ofNullable(passed);
            return this;
        }

        @JsonSetter(value = "benchmark", nulls = Nulls.SKIP)
        public Builder benchmark(Optional<String> benchmark) {
            this.benchmark = benchmark;
            return this;
        }

        public Builder benchmark(String benchmark) {
            this.benchmark = Optional.ofNullable(benchmark);
            return this;
        }

        @JsonSetter(value = "benchmark_run_id", nulls = Nulls.SKIP)
        public Builder benchmarkRunId(Optional<String> benchmarkRunId) {
            this.benchmarkRunId = benchmarkRunId;
            return this;
        }

        public Builder benchmarkRunId(String benchmarkRunId) {
            this.benchmarkRunId = Optional.ofNullable(benchmarkRunId);
            return this;
        }

        @JsonSetter(value = "benchmark_question_id", nulls = Nulls.SKIP)
        public Builder benchmarkQuestionId(Optional<String> benchmarkQuestionId) {
            this.benchmarkQuestionId = benchmarkQuestionId;
            return this;
        }

        public Builder benchmarkQuestionId(String benchmarkQuestionId) {
            this.benchmarkQuestionId = Optional.ofNullable(benchmarkQuestionId);
            return this;
        }

        public ListEvaluationsRequest build() {
            return new ListEvaluationsRequest(
                    page,
                    perPage,
                    minTimestamp,
                    maxTimestamp,
                    minDuration,
                    maxDuration,
                    minScore,
                    maxScore,
                    passed,
                    benchmark,
                    benchmarkRunId,
                    benchmarkQuestionId,
                    additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
