/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.ai.api.resources.corpus.requests;

import com.apologist.ai.api.core.Nullable;
import com.apologist.ai.api.core.NullableNonemptyFilter;
import com.apologist.ai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ImpressionRequest.Builder.class)
public final class ImpressionRequest {
    private final String promptId;

    private final Optional<String> userId;

    private final Map<String, Object> additionalProperties;

    private ImpressionRequest(String promptId, Optional<String> userId, Map<String, Object> additionalProperties) {
        this.promptId = promptId;
        this.userId = userId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("prompt_id")
    public String getPromptId() {
        return promptId;
    }

    @JsonIgnore
    public Optional<String> getUserId() {
        if (userId == null) {
            return Optional.empty();
        }
        return userId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("user_id")
    private Optional<String> _getUserId() {
        return userId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ImpressionRequest && equalTo((ImpressionRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ImpressionRequest other) {
        return promptId.equals(other.promptId) && userId.equals(other.userId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.promptId, this.userId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PromptIdStage builder() {
        return new Builder();
    }

    public interface PromptIdStage {
        _FinalStage promptId(@NotNull String promptId);

        Builder from(ImpressionRequest other);
    }

    public interface _FinalStage {
        ImpressionRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage userId(Optional<String> userId);

        _FinalStage userId(String userId);

        _FinalStage userId(Nullable<String> userId);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PromptIdStage, _FinalStage {
        private String promptId;

        private Optional<String> userId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ImpressionRequest other) {
            promptId(other.getPromptId());
            userId(other.getUserId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("prompt_id")
        public _FinalStage promptId(@NotNull String promptId) {
            this.promptId = Objects.requireNonNull(promptId, "promptId must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage userId(Nullable<String> userId) {
            if (userId.isNull()) {
                this.userId = null;
            } else if (userId.isEmpty()) {
                this.userId = Optional.empty();
            } else {
                this.userId = Optional.of(userId.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "user_id", nulls = Nulls.SKIP)
        public _FinalStage userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        @java.lang.Override
        public ImpressionRequest build() {
            return new ImpressionRequest(promptId, userId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
