/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.ai.api.resources.corpus.requests;

import com.apologist.ai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = LogCorpusReferralRedirectRequest.Builder.class)
public final class LogCorpusReferralRedirectRequest {
    private final String promptId;

    private final Optional<String> userId;

    private final Optional<String> url;

    private final Map<String, Object> additionalProperties;

    private LogCorpusReferralRedirectRequest(
            String promptId, Optional<String> userId, Optional<String> url, Map<String, Object> additionalProperties) {
        this.promptId = promptId;
        this.userId = userId;
        this.url = url;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("prompt_id")
    public String getPromptId() {
        return promptId;
    }

    @JsonProperty("user_id")
    public Optional<String> getUserId() {
        return userId;
    }

    /**
     * @return URL-encoded destination to redirect to after logging the referral.
     */
    @JsonProperty("url")
    public Optional<String> getUrl() {
        return url;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof LogCorpusReferralRedirectRequest && equalTo((LogCorpusReferralRedirectRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(LogCorpusReferralRedirectRequest other) {
        return promptId.equals(other.promptId) && userId.equals(other.userId) && url.equals(other.url);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.promptId, this.userId, this.url);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PromptIdStage builder() {
        return new Builder();
    }

    public interface PromptIdStage {
        _FinalStage promptId(@NotNull String promptId);

        Builder from(LogCorpusReferralRedirectRequest other);
    }

    public interface _FinalStage {
        LogCorpusReferralRedirectRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage userId(Optional<String> userId);

        _FinalStage userId(String userId);

        /**
         * <p>URL-encoded destination to redirect to after logging the referral.</p>
         */
        _FinalStage url(Optional<String> url);

        _FinalStage url(String url);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PromptIdStage, _FinalStage {
        private String promptId;

        private Optional<String> url = Optional.empty();

        private Optional<String> userId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(LogCorpusReferralRedirectRequest other) {
            promptId(other.getPromptId());
            userId(other.getUserId());
            url(other.getUrl());
            return this;
        }

        @java.lang.Override
        @JsonSetter("prompt_id")
        public _FinalStage promptId(@NotNull String promptId) {
            this.promptId = Objects.requireNonNull(promptId, "promptId must not be null");
            return this;
        }

        /**
         * <p>URL-encoded destination to redirect to after logging the referral.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage url(String url) {
            this.url = Optional.ofNullable(url);
            return this;
        }

        /**
         * <p>URL-encoded destination to redirect to after logging the referral.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "url", nulls = Nulls.SKIP)
        public _FinalStage url(Optional<String> url) {
            this.url = url;
            return this;
        }

        @java.lang.Override
        public _FinalStage userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "user_id", nulls = Nulls.SKIP)
        public _FinalStage userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        @java.lang.Override
        public LogCorpusReferralRedirectRequest build() {
            return new LogCorpusReferralRedirectRequest(promptId, userId, url, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
