/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.resources.chat.requests;

import com.apologist.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = FlagRequest.Builder.class)
public final class FlagRequest {
    private final boolean flagged;

    private final Map<String, Object> additionalProperties;

    private FlagRequest(boolean flagged, Map<String, Object> additionalProperties) {
        this.flagged = flagged;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("flagged")
    public boolean getFlagged() {
        return flagged;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof FlagRequest && equalTo((FlagRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(FlagRequest other) {
        return flagged == other.flagged;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.flagged);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FlaggedStage builder() {
        return new Builder();
    }

    public interface FlaggedStage {
        _FinalStage flagged(boolean flagged);

        Builder from(FlagRequest other);
    }

    public interface _FinalStage {
        FlagRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FlaggedStage, _FinalStage {
        private boolean flagged;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(FlagRequest other) {
            flagged(other.getFlagged());
            return this;
        }

        @java.lang.Override
        @JsonSetter("flagged")
        public _FinalStage flagged(boolean flagged) {
            this.flagged = flagged;
            return this;
        }

        @java.lang.Override
        public FlagRequest build() {
            return new FlagRequest(flagged, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
