/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.resources.ctas.types;

import com.apologist.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = MatchCtasResponse.Builder.class)
public final class MatchCtasResponse {
    private final Optional<List<Map<String, Object>>> ctas;

    private final Map<String, Object> additionalProperties;

    private MatchCtasResponse(Optional<List<Map<String, Object>>> ctas, Map<String, Object> additionalProperties) {
        this.ctas = ctas;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("ctas")
    public Optional<List<Map<String, Object>>> getCtas() {
        return ctas;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof MatchCtasResponse && equalTo((MatchCtasResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(MatchCtasResponse other) {
        return ctas.equals(other.ctas);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.ctas);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<Map<String, Object>>> ctas = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(MatchCtasResponse other) {
            ctas(other.getCtas());
            return this;
        }

        @JsonSetter(value = "ctas", nulls = Nulls.SKIP)
        public Builder ctas(Optional<List<Map<String, Object>>> ctas) {
            this.ctas = ctas;
            return this;
        }

        public Builder ctas(List<Map<String, Object>> ctas) {
            this.ctas = Optional.ofNullable(ctas);
            return this;
        }

        public MatchCtasResponse build() {
            return new MatchCtasResponse(ctas, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
