/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.api.types;

import com.apologist.api.core.Nullable;
import com.apologist.api.core.NullableNonemptyFilter;
import com.apologist.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ChatCompletionRequestResponseFormat.Builder.class)
public final class ChatCompletionRequestResponseFormat {
    private final Optional<ChatCompletionRequestResponseFormatType> type;

    private final Optional<ChatCompletionRequestResponseFormatJsonSchema> jsonSchema;

    private final Map<String, Object> additionalProperties;

    private ChatCompletionRequestResponseFormat(
            Optional<ChatCompletionRequestResponseFormatType> type,
            Optional<ChatCompletionRequestResponseFormatJsonSchema> jsonSchema,
            Map<String, Object> additionalProperties) {
        this.type = type;
        this.jsonSchema = jsonSchema;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<ChatCompletionRequestResponseFormatType> getType() {
        if (type == null) {
            return Optional.empty();
        }
        return type;
    }

    /**
     * @return Required when type is json_schema. Supplies the JSON Schema the structured output must conform to. Structured outputs are non-streaming.
     */
    @JsonIgnore
    public Optional<ChatCompletionRequestResponseFormatJsonSchema> getJsonSchema() {
        if (jsonSchema == null) {
            return Optional.empty();
        }
        return jsonSchema;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("type")
    private Optional<ChatCompletionRequestResponseFormatType> _getType() {
        return type;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("json_schema")
    private Optional<ChatCompletionRequestResponseFormatJsonSchema> _getJsonSchema() {
        return jsonSchema;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ChatCompletionRequestResponseFormat
                && equalTo((ChatCompletionRequestResponseFormat) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ChatCompletionRequestResponseFormat other) {
        return type.equals(other.type) && jsonSchema.equals(other.jsonSchema);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.type, this.jsonSchema);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<ChatCompletionRequestResponseFormatType> type = Optional.empty();

        private Optional<ChatCompletionRequestResponseFormatJsonSchema> jsonSchema = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ChatCompletionRequestResponseFormat other) {
            type(other.getType());
            jsonSchema(other.getJsonSchema());
            return this;
        }

        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<ChatCompletionRequestResponseFormatType> type) {
            this.type = type;
            return this;
        }

        public Builder type(ChatCompletionRequestResponseFormatType type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        public Builder type(Nullable<ChatCompletionRequestResponseFormatType> type) {
            if (type.isNull()) {
                this.type = null;
            } else if (type.isEmpty()) {
                this.type = Optional.empty();
            } else {
                this.type = Optional.of(type.get());
            }
            return this;
        }

        /**
         * <p>Required when type is json_schema. Supplies the JSON Schema the structured output must conform to. Structured outputs are non-streaming.</p>
         */
        @JsonSetter(value = "json_schema", nulls = Nulls.SKIP)
        public Builder jsonSchema(Optional<ChatCompletionRequestResponseFormatJsonSchema> jsonSchema) {
            this.jsonSchema = jsonSchema;
            return this;
        }

        public Builder jsonSchema(ChatCompletionRequestResponseFormatJsonSchema jsonSchema) {
            this.jsonSchema = Optional.ofNullable(jsonSchema);
            return this;
        }

        public Builder jsonSchema(Nullable<ChatCompletionRequestResponseFormatJsonSchema> jsonSchema) {
            if (jsonSchema.isNull()) {
                this.jsonSchema = null;
            } else if (jsonSchema.isEmpty()) {
                this.jsonSchema = Optional.empty();
            } else {
                this.jsonSchema = Optional.of(jsonSchema.get());
            }
            return this;
        }

        public ChatCompletionRequestResponseFormat build() {
            return new ChatCompletionRequestResponseFormat(type, jsonSchema, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
