/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.api.resources.ctas;

import com.apologist.api.core.ClientOptions;
import com.apologist.api.core.RequestOptions;
import com.apologist.api.resources.ctas.requests.CtaClickRequest;
import com.apologist.api.resources.ctas.types.MatchCtasResponse;
import com.apologist.api.types.CtaMatchRequest;
import com.apologist.api.types.SuccessResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncCtAsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawCtAsClient rawClient;

    public AsyncCtAsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawCtAsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawCtAsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Finds matching CTAs based on conversation context, user, session, device, or messages
     */
    public CompletableFuture<MatchCtasResponse> matchCtas(CtaMatchRequest request) {
        return this.rawClient.matchCtas(request).thenApply(response -> response.body());
    }

    /**
     * Finds matching CTAs based on conversation context, user, session, device, or messages
     */
    public CompletableFuture<MatchCtasResponse> matchCtas(CtaMatchRequest request, RequestOptions requestOptions) {
        return this.rawClient.matchCtas(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Records that a user clicked on a specific CTA
     */
    public CompletableFuture<SuccessResponse> logCtaClick(String id, CtaClickRequest request) {
        return this.rawClient.logCtaClick(id, request).thenApply(response -> response.body());
    }

    /**
     * Records that a user clicked on a specific CTA
     */
    public CompletableFuture<SuccessResponse> logCtaClick(
            String id, CtaClickRequest request, RequestOptions requestOptions) {
        return this.rawClient.logCtaClick(id, request, requestOptions).thenApply(response -> response.body());
    }
}
