/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.ai.api.resources.shares;

import com.apologist.ai.api.core.ApologistAiApiApiException;
import com.apologist.ai.api.core.ApologistAiApiException;
import com.apologist.ai.api.core.ApologistAiApiHttpResponse;
import com.apologist.ai.api.core.ClientOptions;
import com.apologist.ai.api.core.ObjectMappers;
import com.apologist.ai.api.core.RequestOptions;
import com.apologist.ai.api.core.RetryInterceptor;
import com.apologist.ai.api.errors.InternalServerError;
import com.apologist.ai.api.errors.ServiceUnavailableError;
import com.apologist.ai.api.resources.shares.requests.GetSharedMessagesRequest;
import com.apologist.ai.api.resources.shares.types.GetSharedMessagesResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawSharesClient {
    protected final ClientOptions clientOptions;

    public AsyncRawSharesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Public, unauthenticated read of the messages behind a share token. The token is the bearer capability and enforces tenant isolation against the host agent. An empty or invalid token yields an empty messages array.
     */
    public CompletableFuture<ApologistAiApiHttpResponse<GetSharedMessagesResponse>> getSharedMessages(String token) {
        return getSharedMessages(token, GetSharedMessagesRequest.builder().build());
    }

    /**
     * Public, unauthenticated read of the messages behind a share token. The token is the bearer capability and enforces tenant isolation against the host agent. An empty or invalid token yields an empty messages array.
     */
    public CompletableFuture<ApologistAiApiHttpResponse<GetSharedMessagesResponse>> getSharedMessages(
            String token, RequestOptions requestOptions) {
        return getSharedMessages(token, GetSharedMessagesRequest.builder().build(), requestOptions);
    }

    /**
     * Public, unauthenticated read of the messages behind a share token. The token is the bearer capability and enforces tenant isolation against the host agent. An empty or invalid token yields an empty messages array.
     */
    public CompletableFuture<ApologistAiApiHttpResponse<GetSharedMessagesResponse>> getSharedMessages(
            String token, GetSharedMessagesRequest request) {
        return getSharedMessages(token, request, null);
    }

    /**
     * Public, unauthenticated read of the messages behind a share token. The token is the bearer capability and enforces tenant isolation against the host agent. An empty or invalid token yields an empty messages array.
     */
    public CompletableFuture<ApologistAiApiHttpResponse<GetSharedMessagesResponse>> getSharedMessages(
            String token, GetSharedMessagesRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("shares")
                .addPathSegment(token);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<ApologistAiApiHttpResponse<GetSharedMessagesResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new ApologistAiApiHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, GetSharedMessagesResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 503:
                                future.completeExceptionally(new ServiceUnavailableError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new ApologistAiApiApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new ApologistAiApiException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(
                            new ApologistAiApiException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new ApologistAiApiException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
