/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.resources.channels.requests;

import com.apologist.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ReceiveTelegramUpdateRequest.Builder.class)
public final class ReceiveTelegramUpdateRequest {
    private final Map<String, Object> body;

    private final Map<String, Object> additionalProperties;

    private ReceiveTelegramUpdateRequest(Map<String, Object> body, Map<String, Object> additionalProperties) {
        this.body = body;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Telegram update payload.
     */
    @JsonProperty("body")
    public Map<String, Object> getBody() {
        return body;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ReceiveTelegramUpdateRequest && equalTo((ReceiveTelegramUpdateRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ReceiveTelegramUpdateRequest other) {
        return body.equals(other.body);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.body);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Map<String, Object> body = new LinkedHashMap<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ReceiveTelegramUpdateRequest other) {
            body(other.getBody());
            return this;
        }

        /**
         * <p>Telegram update payload.</p>
         */
        @JsonSetter(value = "body", nulls = Nulls.SKIP)
        public Builder body(Map<String, Object> body) {
            this.body.clear();
            if (body != null) {
                this.body.putAll(body);
            }
            return this;
        }

        public Builder putAllBody(Map<String, Object> body) {
            if (body != null) {
                this.body.putAll(body);
            }
            return this;
        }

        public Builder body(String key, Object value) {
            this.body.put(key, value);
            return this;
        }

        public ReceiveTelegramUpdateRequest build() {
            return new ReceiveTelegramUpdateRequest(body, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
