/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist;

import ai.apologist.core.ClientOptions;
import ai.apologist.core.Suppliers;
import ai.apologist.resources.benchmarks.BenchmarksClient;
import ai.apologist.resources.channels.ChannelsClient;
import ai.apologist.resources.chat.ChatClient;
import ai.apologist.resources.conversations.ConversationsClient;
import ai.apologist.resources.corpus.CorpusClient;
import ai.apologist.resources.ctas.CtAsClient;
import ai.apologist.resources.evaluators.EvaluatorsClient;
import ai.apologist.resources.shares.SharesClient;
import ai.apologist.resources.users.UsersClient;
import java.util.function.Supplier;

public class AgentClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<ChatClient> chatClient;

    protected final Supplier<CorpusClient> corpusClient;

    protected final Supplier<EvaluatorsClient> evaluatorsClient;

    protected final Supplier<CtAsClient> ctAsClient;

    protected final Supplier<UsersClient> usersClient;

    protected final Supplier<BenchmarksClient> benchmarksClient;

    protected final Supplier<ai.apologist.resources.agent.AgentClient> agentClient;

    protected final Supplier<ConversationsClient> conversationsClient;

    protected final Supplier<ChannelsClient> channelsClient;

    protected final Supplier<SharesClient> sharesClient;

    public AgentClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.chatClient = Suppliers.memoize(() -> new ChatClient(clientOptions));
        this.corpusClient = Suppliers.memoize(() -> new CorpusClient(clientOptions));
        this.evaluatorsClient = Suppliers.memoize(() -> new EvaluatorsClient(clientOptions));
        this.ctAsClient = Suppliers.memoize(() -> new CtAsClient(clientOptions));
        this.usersClient = Suppliers.memoize(() -> new UsersClient(clientOptions));
        this.benchmarksClient = Suppliers.memoize(() -> new BenchmarksClient(clientOptions));
        this.agentClient = Suppliers.memoize(() -> new ai.apologist.resources.agent.AgentClient(clientOptions));
        this.conversationsClient = Suppliers.memoize(() -> new ConversationsClient(clientOptions));
        this.channelsClient = Suppliers.memoize(() -> new ChannelsClient(clientOptions));
        this.sharesClient = Suppliers.memoize(() -> new SharesClient(clientOptions));
    }

    public ChatClient chat() {
        return this.chatClient.get();
    }

    public CorpusClient corpus() {
        return this.corpusClient.get();
    }

    public EvaluatorsClient evaluators() {
        return this.evaluatorsClient.get();
    }

    public CtAsClient ctAs() {
        return this.ctAsClient.get();
    }

    public UsersClient users() {
        return this.usersClient.get();
    }

    public BenchmarksClient benchmarks() {
        return this.benchmarksClient.get();
    }

    public ai.apologist.resources.agent.AgentClient agent() {
        return this.agentClient.get();
    }

    public ConversationsClient conversations() {
        return this.conversationsClient.get();
    }

    public ChannelsClient channels() {
        return this.channelsClient.get();
    }

    public SharesClient shares() {
        return this.sharesClient.get();
    }

    public static AgentClientBuilder builder() {
        return new AgentClientBuilder();
    }
}
