/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.resources.ctas;

import ai.apologist.core.AgentClientApiException;
import ai.apologist.core.AgentClientException;
import ai.apologist.core.AgentClientHttpResponse;
import ai.apologist.core.ClientOptions;
import ai.apologist.core.MediaTypes;
import ai.apologist.core.ObjectMappers;
import ai.apologist.core.RequestOptions;
import ai.apologist.core.RetryInterceptor;
import ai.apologist.errors.ForbiddenError;
import ai.apologist.errors.InternalServerError;
import ai.apologist.errors.ServiceUnavailableError;
import ai.apologist.errors.UnprocessableEntityError;
import ai.apologist.resources.ctas.requests.CtaClickRequest;
import ai.apologist.resources.ctas.types.MatchCtasResponse;
import ai.apologist.types.CtaMatchRequest;
import ai.apologist.types.Error;
import ai.apologist.types.SuccessResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawCtAsClient {
    protected final ClientOptions clientOptions;

    public RawCtAsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Finds matching CTAs based on conversation context, user, session, device, or messages
     */
    public AgentClientHttpResponse<MatchCtasResponse> matchCtas(CtaMatchRequest request) {
        return matchCtas(request, null);
    }

    /**
     * Finds matching CTAs based on conversation context, user, session, device, or messages
     */
    public AgentClientHttpResponse<MatchCtasResponse> matchCtas(
            CtaMatchRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("ctas/match");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new AgentClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new AgentClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, MatchCtasResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 503:
                        throw new ServiceUnavailableError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new AgentClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new AgentClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new AgentClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Records that a user clicked on a specific CTA
     */
    public AgentClientHttpResponse<SuccessResponse> logCtaClick(String id, CtaClickRequest request) {
        return logCtaClick(id, request, null);
    }

    /**
     * Records that a user clicked on a specific CTA
     */
    public AgentClientHttpResponse<SuccessResponse> logCtaClick(
            String id, CtaClickRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("ctas")
                .addPathSegment(id)
                .addPathSegments("click");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new AgentClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new AgentClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, SuccessResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 503:
                        throw new ServiceUnavailableError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new AgentClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new AgentClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new AgentClientException("Network error executing HTTP request", e);
        }
    }
}
