/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.resources.users.types;

import ai.apologist.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.util.Objects;

@JsonDeserialize(using = UserUpdateRequestTagsItem.Deserializer.class)
public final class UserUpdateRequestTagsItem {
    private final Object value;

    private final int type;

    private UserUpdateRequestTagsItem(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((String) this.value);
        } else if (this.type == 1) {
            return visitor.visit((int) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UserUpdateRequestTagsItem && equalTo((UserUpdateRequestTagsItem) other);
    }

    private boolean equalTo(UserUpdateRequestTagsItem other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static UserUpdateRequestTagsItem of(String value) {
        return new UserUpdateRequestTagsItem(value, 0);
    }

    public static UserUpdateRequestTagsItem of(int value) {
        return new UserUpdateRequestTagsItem(value, 1);
    }

    public interface Visitor<T> {
        T visit(String value);

        T visit(int value);
    }

    static final class Deserializer extends StdDeserializer<UserUpdateRequestTagsItem> {
        Deserializer() {
            super(UserUpdateRequestTagsItem.class);
        }

        @java.lang.Override
        public UserUpdateRequestTagsItem deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            if (value instanceof Integer) {
                return of((Integer) value);
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, String.class));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
