/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ChatCompletionRequestVerbosity {
    public static final ChatCompletionRequestVerbosity MEDIUM =
            new ChatCompletionRequestVerbosity(Value.MEDIUM, "medium");

    public static final ChatCompletionRequestVerbosity LOW = new ChatCompletionRequestVerbosity(Value.LOW, "low");

    public static final ChatCompletionRequestVerbosity MINIMAL =
            new ChatCompletionRequestVerbosity(Value.MINIMAL, "minimal");

    public static final ChatCompletionRequestVerbosity HIGH = new ChatCompletionRequestVerbosity(Value.HIGH, "high");

    private final Value value;

    private final String string;

    ChatCompletionRequestVerbosity(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ChatCompletionRequestVerbosity
                        && this.string.equals(((ChatCompletionRequestVerbosity) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case MEDIUM:
                return visitor.visitMedium();
            case LOW:
                return visitor.visitLow();
            case MINIMAL:
                return visitor.visitMinimal();
            case HIGH:
                return visitor.visitHigh();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ChatCompletionRequestVerbosity valueOf(String value) {
        switch (value) {
            case "medium":
                return MEDIUM;
            case "low":
                return LOW;
            case "minimal":
                return MINIMAL;
            case "high":
                return HIGH;
            default:
                return new ChatCompletionRequestVerbosity(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        MINIMAL,

        LOW,

        MEDIUM,

        HIGH,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitMinimal();

        T visitLow();

        T visitMedium();

        T visitHigh();

        T visitUnknown(String unknownType);
    }
}
