/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.types;

import ai.apologist.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonDeserialize(using = ChatCompletionRequestToolChoice.Deserializer.class)
public final class ChatCompletionRequestToolChoice {
    private final Object value;

    private final int type;

    private ChatCompletionRequestToolChoice(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((ChatCompletionRequestToolChoiceZero) this.value);
        } else if (this.type == 1) {
            return visitor.visit((Optional<Map<String, Object>>) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ChatCompletionRequestToolChoice && equalTo((ChatCompletionRequestToolChoice) other);
    }

    private boolean equalTo(ChatCompletionRequestToolChoice other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static ChatCompletionRequestToolChoice of(ChatCompletionRequestToolChoiceZero value) {
        return new ChatCompletionRequestToolChoice(value, 0);
    }

    public static ChatCompletionRequestToolChoice of(Optional<Map<String, Object>> value) {
        return new ChatCompletionRequestToolChoice(value, 1);
    }

    public interface Visitor<T> {
        T visit(ChatCompletionRequestToolChoiceZero value);

        T visit(Optional<Map<String, Object>> value);
    }

    static final class Deserializer extends StdDeserializer<ChatCompletionRequestToolChoice> {
        Deserializer() {
            super(ChatCompletionRequestToolChoice.class);
        }

        @java.lang.Override
        public ChatCompletionRequestToolChoice deserialize(JsonParser p, DeserializationContext context)
                throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, ChatCompletionRequestToolChoiceZero.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(
                        value, new TypeReference<Optional<Map<String, Object>>>() {}));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
