/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class UserRedactResponseMode {
    public static final UserRedactResponseMode ANONYMIZE = new UserRedactResponseMode(Value.ANONYMIZE, "anonymize");

    public static final UserRedactResponseMode SCRUB = new UserRedactResponseMode(Value.SCRUB, "scrub");

    private final Value value;

    private final String string;

    UserRedactResponseMode(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof UserRedactResponseMode
                        && this.string.equals(((UserRedactResponseMode) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case ANONYMIZE:
                return visitor.visitAnonymize();
            case SCRUB:
                return visitor.visitScrub();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static UserRedactResponseMode valueOf(String value) {
        switch (value) {
            case "anonymize":
                return ANONYMIZE;
            case "scrub":
                return SCRUB;
            default:
                return new UserRedactResponseMode(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        SCRUB,

        ANONYMIZE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitScrub();

        T visitAnonymize();

        T visitUnknown(String unknownType);
    }
}
