/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.types;

import ai.apologist.core.Nullable;
import ai.apologist.core.NullableNonemptyFilter;
import ai.apologist.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UserRedactResponse.Builder.class)
public final class UserRedactResponse {
    private final Optional<String> id;

    private final Optional<UserRedactResponseMode> mode;

    private final Optional<String> redactRequestedAt;

    private final Optional<Integer> messagesRedacted;

    private final Optional<Integer> remaining;

    private final Map<String, Object> additionalProperties;

    private UserRedactResponse(
            Optional<String> id,
            Optional<UserRedactResponseMode> mode,
            Optional<String> redactRequestedAt,
            Optional<Integer> messagesRedacted,
            Optional<Integer> remaining,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.mode = mode;
        this.redactRequestedAt = redactRequestedAt;
        this.messagesRedacted = messagesRedacted;
        this.remaining = remaining;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Internal user id (UUID).
     */
    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    @JsonProperty("mode")
    public Optional<UserRedactResponseMode> getMode() {
        return mode;
    }

    /**
     * @return When the erase request was stamped. The hourly cron finishes leftover rows.
     */
    @JsonIgnore
    public Optional<String> getRedactRequestedAt() {
        if (redactRequestedAt == null) {
            return Optional.empty();
        }
        return redactRequestedAt;
    }

    /**
     * @return Message rows rewritten in this request.
     */
    @JsonProperty("messages_redacted")
    public Optional<Integer> getMessagesRedacted() {
        return messagesRedacted;
    }

    /**
     * @return Message rows still waiting. Zero means this request finished the user.
     */
    @JsonProperty("remaining")
    public Optional<Integer> getRemaining() {
        return remaining;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("redact_requested_at")
    private Optional<String> _getRedactRequestedAt() {
        return redactRequestedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UserRedactResponse && equalTo((UserRedactResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UserRedactResponse other) {
        return id.equals(other.id)
                && mode.equals(other.mode)
                && redactRequestedAt.equals(other.redactRequestedAt)
                && messagesRedacted.equals(other.messagesRedacted)
                && remaining.equals(other.remaining);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.mode, this.redactRequestedAt, this.messagesRedacted, this.remaining);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> id = Optional.empty();

        private Optional<UserRedactResponseMode> mode = Optional.empty();

        private Optional<String> redactRequestedAt = Optional.empty();

        private Optional<Integer> messagesRedacted = Optional.empty();

        private Optional<Integer> remaining = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UserRedactResponse other) {
            id(other.getId());
            mode(other.getMode());
            redactRequestedAt(other.getRedactRequestedAt());
            messagesRedacted(other.getMessagesRedacted());
            remaining(other.getRemaining());
            return this;
        }

        /**
         * <p>Internal user id (UUID).</p>
         */
        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        @JsonSetter(value = "mode", nulls = Nulls.SKIP)
        public Builder mode(Optional<UserRedactResponseMode> mode) {
            this.mode = mode;
            return this;
        }

        public Builder mode(UserRedactResponseMode mode) {
            this.mode = Optional.ofNullable(mode);
            return this;
        }

        /**
         * <p>When the erase request was stamped. The hourly cron finishes leftover rows.</p>
         */
        @JsonSetter(value = "redact_requested_at", nulls = Nulls.SKIP)
        public Builder redactRequestedAt(Optional<String> redactRequestedAt) {
            this.redactRequestedAt = redactRequestedAt;
            return this;
        }

        public Builder redactRequestedAt(String redactRequestedAt) {
            this.redactRequestedAt = Optional.ofNullable(redactRequestedAt);
            return this;
        }

        public Builder redactRequestedAt(Nullable<String> redactRequestedAt) {
            if (redactRequestedAt.isNull()) {
                this.redactRequestedAt = null;
            } else if (redactRequestedAt.isEmpty()) {
                this.redactRequestedAt = Optional.empty();
            } else {
                this.redactRequestedAt = Optional.of(redactRequestedAt.get());
            }
            return this;
        }

        /**
         * <p>Message rows rewritten in this request.</p>
         */
        @JsonSetter(value = "messages_redacted", nulls = Nulls.SKIP)
        public Builder messagesRedacted(Optional<Integer> messagesRedacted) {
            this.messagesRedacted = messagesRedacted;
            return this;
        }

        public Builder messagesRedacted(Integer messagesRedacted) {
            this.messagesRedacted = Optional.ofNullable(messagesRedacted);
            return this;
        }

        /**
         * <p>Message rows still waiting. Zero means this request finished the user.</p>
         */
        @JsonSetter(value = "remaining", nulls = Nulls.SKIP)
        public Builder remaining(Optional<Integer> remaining) {
            this.remaining = remaining;
            return this;
        }

        public Builder remaining(Integer remaining) {
            this.remaining = Optional.ofNullable(remaining);
            return this;
        }

        public UserRedactResponse build() {
            return new UserRedactResponse(
                    id, mode, redactRequestedAt, messagesRedacted, remaining, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
