/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.resources.shares;

import ai.apologist.core.AgentClientApiException;
import ai.apologist.core.AgentClientException;
import ai.apologist.core.AgentClientHttpResponse;
import ai.apologist.core.ClientOptions;
import ai.apologist.core.ObjectMappers;
import ai.apologist.core.RequestOptions;
import ai.apologist.core.RetryInterceptor;
import ai.apologist.errors.InternalServerError;
import ai.apologist.errors.ServiceUnavailableError;
import ai.apologist.resources.shares.requests.GetSharedMessagesRequest;
import ai.apologist.resources.shares.types.GetSharedMessagesResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawSharesClient {
    protected final ClientOptions clientOptions;

    public RawSharesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Public, unauthenticated read of the messages behind a share token. The token is the bearer capability and enforces tenant isolation against the host agent. An empty or invalid token yields an empty messages array.
     */
    public AgentClientHttpResponse<GetSharedMessagesResponse> getSharedMessages(String token) {
        return getSharedMessages(token, GetSharedMessagesRequest.builder().build());
    }

    /**
     * Public, unauthenticated read of the messages behind a share token. The token is the bearer capability and enforces tenant isolation against the host agent. An empty or invalid token yields an empty messages array.
     */
    public AgentClientHttpResponse<GetSharedMessagesResponse> getSharedMessages(
            String token, RequestOptions requestOptions) {
        return getSharedMessages(token, GetSharedMessagesRequest.builder().build(), requestOptions);
    }

    /**
     * Public, unauthenticated read of the messages behind a share token. The token is the bearer capability and enforces tenant isolation against the host agent. An empty or invalid token yields an empty messages array.
     */
    public AgentClientHttpResponse<GetSharedMessagesResponse> getSharedMessages(
            String token, GetSharedMessagesRequest request) {
        return getSharedMessages(token, request, null);
    }

    /**
     * Public, unauthenticated read of the messages behind a share token. The token is the bearer capability and enforces tenant isolation against the host agent. An empty or invalid token yields an empty messages array.
     */
    public AgentClientHttpResponse<GetSharedMessagesResponse> getSharedMessages(
            String token, GetSharedMessagesRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("shares")
                .addPathSegment(token);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new AgentClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetSharedMessagesResponse.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 503:
                        throw new ServiceUnavailableError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new AgentClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new AgentClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new AgentClientException("Network error executing HTTP request", e);
        }
    }
}
