/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.ai.api.resources.users;

import com.apologist.ai.api.core.ApologistAiApiApiException;
import com.apologist.ai.api.core.ApologistAiApiException;
import com.apologist.ai.api.core.ApologistAiApiHttpResponse;
import com.apologist.ai.api.core.ClientOptions;
import com.apologist.ai.api.core.MediaTypes;
import com.apologist.ai.api.core.ObjectMappers;
import com.apologist.ai.api.core.QueryStringMapper;
import com.apologist.ai.api.core.RequestOptions;
import com.apologist.ai.api.core.RetryInterceptor;
import com.apologist.ai.api.errors.BadRequestError;
import com.apologist.ai.api.errors.ForbiddenError;
import com.apologist.ai.api.errors.InternalServerError;
import com.apologist.ai.api.errors.NotFoundError;
import com.apologist.ai.api.errors.UnprocessableEntityError;
import com.apologist.ai.api.resources.users.requests.GetUserRequest;
import com.apologist.ai.api.resources.users.requests.ListUserFlagsRequest;
import com.apologist.ai.api.resources.users.requests.ListUsersRequest;
import com.apologist.ai.api.resources.users.requests.UserUpdateRequest;
import com.apologist.ai.api.resources.users.types.GetUserResponse;
import com.apologist.ai.api.resources.users.types.ListUserFlagsResponse;
import com.apologist.ai.api.resources.users.types.ListUsersResponse;
import com.apologist.ai.api.resources.users.types.UpdateUserResponse;
import com.apologist.ai.api.types.Error;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawUsersClient {
    protected final ClientOptions clientOptions;

    public RawUsersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns a paginated list of users for the agent's team, with applied tags expanded as { id, name } and the persisted responder id.
     */
    public ApologistAiApiHttpResponse<ListUsersResponse> listUsers() {
        return listUsers(ListUsersRequest.builder().build());
    }

    /**
     * Returns a paginated list of users for the agent's team, with applied tags expanded as { id, name } and the persisted responder id.
     */
    public ApologistAiApiHttpResponse<ListUsersResponse> listUsers(RequestOptions requestOptions) {
        return listUsers(ListUsersRequest.builder().build(), requestOptions);
    }

    /**
     * Returns a paginated list of users for the agent's team, with applied tags expanded as { id, name } and the persisted responder id.
     */
    public ApologistAiApiHttpResponse<ListUsersResponse> listUsers(ListUsersRequest request) {
        return listUsers(request, null);
    }

    /**
     * Returns a paginated list of users for the agent's team, with applied tags expanded as { id, name } and the persisted responder id.
     */
    public ApologistAiApiHttpResponse<ListUsersResponse> listUsers(
            ListUsersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users");
        if (request.getPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getPerPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "per_page", request.getPerPage().get(), false);
        }
        if (request.getExternalId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "external_id", request.getExternalId().get(), false);
        }
        if (request.getTags().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "tags", request.getTags().get(), false);
        }
        if (request.getResponderId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "responder_id", request.getResponderId().get(), false);
        }
        if (request.getMinTimestamp().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "min_timestamp", request.getMinTimestamp().get(), false);
        }
        if (request.getMaxTimestamp().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "max_timestamp", request.getMaxTimestamp().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ApologistAiApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListUsersResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApologistAiApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new ApologistAiApiException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new ApologistAiApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns a paginated list of user flag definitions for the agent's team (all columns from user_flags), ordered by id ascending.
     */
    public ApologistAiApiHttpResponse<ListUserFlagsResponse> listUserFlags() {
        return listUserFlags(ListUserFlagsRequest.builder().build());
    }

    /**
     * Returns a paginated list of user flag definitions for the agent's team (all columns from user_flags), ordered by id ascending.
     */
    public ApologistAiApiHttpResponse<ListUserFlagsResponse> listUserFlags(RequestOptions requestOptions) {
        return listUserFlags(ListUserFlagsRequest.builder().build(), requestOptions);
    }

    /**
     * Returns a paginated list of user flag definitions for the agent's team (all columns from user_flags), ordered by id ascending.
     */
    public ApologistAiApiHttpResponse<ListUserFlagsResponse> listUserFlags(ListUserFlagsRequest request) {
        return listUserFlags(request, null);
    }

    /**
     * Returns a paginated list of user flag definitions for the agent's team (all columns from user_flags), ordered by id ascending.
     */
    public ApologistAiApiHttpResponse<ListUserFlagsResponse> listUserFlags(
            ListUserFlagsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users/flags");
        if (request.getPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getPerPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "per_page", request.getPerPage().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ApologistAiApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListUserFlagsResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApologistAiApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new ApologistAiApiException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new ApologistAiApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns a single user by external id or internal id, with expanded tags and the persisted responder for the agent.
     */
    public ApologistAiApiHttpResponse<GetUserResponse> getUser(String userId) {
        return getUser(userId, GetUserRequest.builder().build());
    }

    /**
     * Returns a single user by external id or internal id, with expanded tags and the persisted responder for the agent.
     */
    public ApologistAiApiHttpResponse<GetUserResponse> getUser(String userId, RequestOptions requestOptions) {
        return getUser(userId, GetUserRequest.builder().build(), requestOptions);
    }

    /**
     * Returns a single user by external id or internal id, with expanded tags and the persisted responder for the agent.
     */
    public ApologistAiApiHttpResponse<GetUserResponse> getUser(String userId, GetUserRequest request) {
        return getUser(userId, request, null);
    }

    /**
     * Returns a single user by external id or internal id, with expanded tags and the persisted responder for the agent.
     */
    public ApologistAiApiHttpResponse<GetUserResponse> getUser(
            String userId, GetUserRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(userId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ApologistAiApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetUserResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApologistAiApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new ApologistAiApiException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new ApologistAiApiException("Network error executing HTTP request", e);
        }
    }

    /**
     * Updates a user's external_id and/or tags and upserts the persisted responder for the agent. Only provided fields are changed.
     */
    public ApologistAiApiHttpResponse<UpdateUserResponse> updateUser(String userId) {
        return updateUser(userId, UserUpdateRequest.builder().build());
    }

    /**
     * Updates a user's external_id and/or tags and upserts the persisted responder for the agent. Only provided fields are changed.
     */
    public ApologistAiApiHttpResponse<UpdateUserResponse> updateUser(String userId, RequestOptions requestOptions) {
        return updateUser(userId, UserUpdateRequest.builder().build(), requestOptions);
    }

    /**
     * Updates a user's external_id and/or tags and upserts the persisted responder for the agent. Only provided fields are changed.
     */
    public ApologistAiApiHttpResponse<UpdateUserResponse> updateUser(String userId, UserUpdateRequest request) {
        return updateUser(userId, request, null);
    }

    /**
     * Updates a user's external_id and/or tags and upserts the persisted responder for the agent. Only provided fields are changed.
     */
    public ApologistAiApiHttpResponse<UpdateUserResponse> updateUser(
            String userId, UserUpdateRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(userId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ApologistAiApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ApologistAiApiHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UpdateUserResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 400:
                        throw new BadRequestError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApologistAiApiApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new ApologistAiApiException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new ApologistAiApiException("Network error executing HTTP request", e);
        }
    }
}
