/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.resources.shares.types;

import ai.apologist.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = GetSharedMessagesResponse.Builder.class)
public final class GetSharedMessagesResponse {
    private final Optional<List<Map<String, Object>>> messages;

    private final Map<String, Object> additionalProperties;

    private GetSharedMessagesResponse(
            Optional<List<Map<String, Object>>> messages, Map<String, Object> additionalProperties) {
        this.messages = messages;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("messages")
    public Optional<List<Map<String, Object>>> getMessages() {
        return messages;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof GetSharedMessagesResponse && equalTo((GetSharedMessagesResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(GetSharedMessagesResponse other) {
        return messages.equals(other.messages);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.messages);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<Map<String, Object>>> messages = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(GetSharedMessagesResponse other) {
            messages(other.getMessages());
            return this;
        }

        @JsonSetter(value = "messages", nulls = Nulls.SKIP)
        public Builder messages(Optional<List<Map<String, Object>>> messages) {
            this.messages = messages;
            return this;
        }

        public Builder messages(List<Map<String, Object>> messages) {
            this.messages = Optional.ofNullable(messages);
            return this;
        }

        public GetSharedMessagesResponse build() {
            return new GetSharedMessagesResponse(messages, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
