/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.api.resources.chat.requests;

import com.apologist.api.core.Nullable;
import com.apologist.api.core.NullableNonemptyFilter;
import com.apologist.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ShareRequest.Builder.class)
public final class ShareRequest {
    private final Optional<String> conversationId;

    private final Optional<String> sessionId;

    private final Optional<String> userId;

    private final Map<String, Object> additionalProperties;

    private ShareRequest(
            Optional<String> conversationId,
            Optional<String> sessionId,
            Optional<String> userId,
            Map<String, Object> additionalProperties) {
        this.conversationId = conversationId;
        this.sessionId = sessionId;
        this.userId = userId;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<String> getConversationId() {
        if (conversationId == null) {
            return Optional.empty();
        }
        return conversationId;
    }

    @JsonIgnore
    public Optional<String> getSessionId() {
        if (sessionId == null) {
            return Optional.empty();
        }
        return sessionId;
    }

    @JsonIgnore
    public Optional<String> getUserId() {
        if (userId == null) {
            return Optional.empty();
        }
        return userId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("conversation_id")
    private Optional<String> _getConversationId() {
        return conversationId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("session_id")
    private Optional<String> _getSessionId() {
        return sessionId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("user_id")
    private Optional<String> _getUserId() {
        return userId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ShareRequest && equalTo((ShareRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ShareRequest other) {
        return conversationId.equals(other.conversationId)
                && sessionId.equals(other.sessionId)
                && userId.equals(other.userId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.conversationId, this.sessionId, this.userId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> conversationId = Optional.empty();

        private Optional<String> sessionId = Optional.empty();

        private Optional<String> userId = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ShareRequest other) {
            conversationId(other.getConversationId());
            sessionId(other.getSessionId());
            userId(other.getUserId());
            return this;
        }

        @JsonSetter(value = "conversation_id", nulls = Nulls.SKIP)
        public Builder conversationId(Optional<String> conversationId) {
            this.conversationId = conversationId;
            return this;
        }

        public Builder conversationId(String conversationId) {
            this.conversationId = Optional.ofNullable(conversationId);
            return this;
        }

        public Builder conversationId(Nullable<String> conversationId) {
            if (conversationId.isNull()) {
                this.conversationId = null;
            } else if (conversationId.isEmpty()) {
                this.conversationId = Optional.empty();
            } else {
                this.conversationId = Optional.of(conversationId.get());
            }
            return this;
        }

        @JsonSetter(value = "session_id", nulls = Nulls.SKIP)
        public Builder sessionId(Optional<String> sessionId) {
            this.sessionId = sessionId;
            return this;
        }

        public Builder sessionId(String sessionId) {
            this.sessionId = Optional.ofNullable(sessionId);
            return this;
        }

        public Builder sessionId(Nullable<String> sessionId) {
            if (sessionId.isNull()) {
                this.sessionId = null;
            } else if (sessionId.isEmpty()) {
                this.sessionId = Optional.empty();
            } else {
                this.sessionId = Optional.of(sessionId.get());
            }
            return this;
        }

        @JsonSetter(value = "user_id", nulls = Nulls.SKIP)
        public Builder userId(Optional<String> userId) {
            this.userId = userId;
            return this;
        }

        public Builder userId(String userId) {
            this.userId = Optional.ofNullable(userId);
            return this;
        }

        public Builder userId(Nullable<String> userId) {
            if (userId.isNull()) {
                this.userId = null;
            } else if (userId.isEmpty()) {
                this.userId = Optional.empty();
            } else {
                this.userId = Optional.of(userId.get());
            }
            return this;
        }

        public ShareRequest build() {
            return new ShareRequest(conversationId, sessionId, userId, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
