/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.api.resources.evaluators.types;

import com.apologist.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import java.io.IOException;
import java.util.List;
import java.util.Objects;

@JsonDeserialize(using = EvaluatorRequestContent.Deserializer.class)
public final class EvaluatorRequestContent {
    private final Object value;

    private final int type;

    private EvaluatorRequestContent(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((String) this.value);
        } else if (this.type == 1) {
            return visitor.visit((List<Object>) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EvaluatorRequestContent && equalTo((EvaluatorRequestContent) other);
    }

    private boolean equalTo(EvaluatorRequestContent other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static EvaluatorRequestContent of(String value) {
        return new EvaluatorRequestContent(value, 0);
    }

    public static EvaluatorRequestContent of(List<Object> value) {
        return new EvaluatorRequestContent(value, 1);
    }

    public interface Visitor<T> {
        T visit(String value);

        T visit(List<Object> value);
    }

    static final class Deserializer extends StdDeserializer<EvaluatorRequestContent> {
        Deserializer() {
            super(EvaluatorRequestContent.class);
        }

        @java.lang.Override
        public EvaluatorRequestContent deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, String.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, new TypeReference<List<Object>>() {}));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
