/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.resources.ctas;

import com.apologist.core.ClientOptions;
import com.apologist.core.RequestOptions;
import com.apologist.resources.ctas.requests.CtaClickRequest;
import com.apologist.resources.ctas.types.MatchCtasResponse;
import com.apologist.types.CtaMatchRequest;
import com.apologist.types.SuccessResponse;

public class CtAsClient {
    protected final ClientOptions clientOptions;

    private final RawCtAsClient rawClient;

    public CtAsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawCtAsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawCtAsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Finds matching CTAs based on conversation context, user, session, device, or messages
     */
    public MatchCtasResponse matchCtas(CtaMatchRequest request) {
        return this.rawClient.matchCtas(request).body();
    }

    /**
     * Finds matching CTAs based on conversation context, user, session, device, or messages
     */
    public MatchCtasResponse matchCtas(CtaMatchRequest request, RequestOptions requestOptions) {
        return this.rawClient.matchCtas(request, requestOptions).body();
    }

    /**
     * Records that a user clicked on a specific CTA
     */
    public SuccessResponse logCtaClick(String id, CtaClickRequest request) {
        return this.rawClient.logCtaClick(id, request).body();
    }

    /**
     * Records that a user clicked on a specific CTA
     */
    public SuccessResponse logCtaClick(String id, CtaClickRequest request, RequestOptions requestOptions) {
        return this.rawClient.logCtaClick(id, request, requestOptions).body();
    }
}
