/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.api.resources.evaluators;

import com.apologist.api.core.ApologistClientApiException;
import com.apologist.api.core.ApologistClientException;
import com.apologist.api.core.ApologistClientHttpResponse;
import com.apologist.api.core.ClientOptions;
import com.apologist.api.core.MediaTypes;
import com.apologist.api.core.ObjectMappers;
import com.apologist.api.core.QueryStringMapper;
import com.apologist.api.core.RequestOptions;
import com.apologist.api.core.RetryInterceptor;
import com.apologist.api.errors.ForbiddenError;
import com.apologist.api.errors.InternalServerError;
import com.apologist.api.errors.NotFoundError;
import com.apologist.api.errors.ServiceUnavailableError;
import com.apologist.api.errors.UnprocessableEntityError;
import com.apologist.api.resources.evaluators.requests.EvaluatorRequest;
import com.apologist.api.resources.evaluators.requests.GetEvaluationRequest;
import com.apologist.api.resources.evaluators.requests.ListEvaluationsRequest;
import com.apologist.api.resources.evaluators.types.EvaluateContentResponse;
import com.apologist.api.resources.evaluators.types.GetEvaluationResponse;
import com.apologist.api.resources.evaluators.types.ListEvaluationsResponse;
import com.apologist.api.types.Error;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawEvaluatorsClient {
    protected final ClientOptions clientOptions;

    public RawEvaluatorsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns a paginated list of evaluations for the evaluator, scoped to the requesting agent.
     */
    public ApologistClientHttpResponse<ListEvaluationsResponse> listEvaluations(String id) {
        return listEvaluations(id, ListEvaluationsRequest.builder().build());
    }

    /**
     * Returns a paginated list of evaluations for the evaluator, scoped to the requesting agent.
     */
    public ApologistClientHttpResponse<ListEvaluationsResponse> listEvaluations(
            String id, RequestOptions requestOptions) {
        return listEvaluations(id, ListEvaluationsRequest.builder().build(), requestOptions);
    }

    /**
     * Returns a paginated list of evaluations for the evaluator, scoped to the requesting agent.
     */
    public ApologistClientHttpResponse<ListEvaluationsResponse> listEvaluations(
            String id, ListEvaluationsRequest request) {
        return listEvaluations(id, request, null);
    }

    /**
     * Returns a paginated list of evaluations for the evaluator, scoped to the requesting agent.
     */
    public ApologistClientHttpResponse<ListEvaluationsResponse> listEvaluations(
            String id, ListEvaluationsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("evaluators")
                .addPathSegment(id)
                .addPathSegments("evaluations");
        if (request.getPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getPerPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "per_page", request.getPerPage().get(), false);
        }
        if (request.getMinTimestamp().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "min_timestamp", request.getMinTimestamp().get(), false);
        }
        if (request.getMaxTimestamp().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "max_timestamp", request.getMaxTimestamp().get(), false);
        }
        if (request.getMinDuration().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "min_duration", request.getMinDuration().get(), false);
        }
        if (request.getMaxDuration().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "max_duration", request.getMaxDuration().get(), false);
        }
        if (request.getMinScore().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "min_score", request.getMinScore().get(), false);
        }
        if (request.getMaxScore().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "max_score", request.getMaxScore().get(), false);
        }
        if (request.getPassed().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "passed", request.getPassed().get(), false);
        }
        if (request.getBenchmark().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "benchmark", request.getBenchmark().get(), false);
        }
        if (request.getBenchmarkRunId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "benchmark_run_id", request.getBenchmarkRunId().get(), false);
        }
        if (request.getBenchmarkQuestionId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl,
                    "benchmark_question_id",
                    request.getBenchmarkQuestionId().get(),
                    false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ApologistClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListEvaluationsResponse.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApologistClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new ApologistClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new ApologistClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Runs an evaluation on the provided content using the specified evaluator
     */
    public ApologistClientHttpResponse<EvaluateContentResponse> evaluateContent(String id, EvaluatorRequest request) {
        return evaluateContent(id, request, null);
    }

    /**
     * Runs an evaluation on the provided content using the specified evaluator
     */
    public ApologistClientHttpResponse<EvaluateContentResponse> evaluateContent(
            String id, EvaluatorRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("evaluators")
                .addPathSegment(id)
                .addPathSegments("evaluations");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new ApologistClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ApologistClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, EvaluateContentResponse.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 503:
                        throw new ServiceUnavailableError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApologistClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new ApologistClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new ApologistClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns a single evaluation for the evaluator, scoped to the requesting agent.
     */
    public ApologistClientHttpResponse<GetEvaluationResponse> getEvaluation(String id, String evaluationId) {
        return getEvaluation(id, evaluationId, GetEvaluationRequest.builder().build());
    }

    /**
     * Returns a single evaluation for the evaluator, scoped to the requesting agent.
     */
    public ApologistClientHttpResponse<GetEvaluationResponse> getEvaluation(
            String id, String evaluationId, RequestOptions requestOptions) {
        return getEvaluation(id, evaluationId, GetEvaluationRequest.builder().build(), requestOptions);
    }

    /**
     * Returns a single evaluation for the evaluator, scoped to the requesting agent.
     */
    public ApologistClientHttpResponse<GetEvaluationResponse> getEvaluation(
            String id, String evaluationId, GetEvaluationRequest request) {
        return getEvaluation(id, evaluationId, request, null);
    }

    /**
     * Returns a single evaluation for the evaluator, scoped to the requesting agent.
     */
    public ApologistClientHttpResponse<GetEvaluationResponse> getEvaluation(
            String id, String evaluationId, GetEvaluationRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("evaluators")
                .addPathSegment(id)
                .addPathSegments("evaluations")
                .addPathSegment(evaluationId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new ApologistClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetEvaluationResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ApologistClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new ApologistClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new ApologistClientException("Network error executing HTTP request", e);
        }
    }
}
