/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.resources.users;

import ai.apologist.core.AgentClientApiException;
import ai.apologist.core.AgentClientException;
import ai.apologist.core.AgentClientHttpResponse;
import ai.apologist.core.ClientOptions;
import ai.apologist.core.MediaTypes;
import ai.apologist.core.ObjectMappers;
import ai.apologist.core.QueryStringMapper;
import ai.apologist.core.RequestOptions;
import ai.apologist.core.RetryInterceptor;
import ai.apologist.errors.BadRequestError;
import ai.apologist.errors.ForbiddenError;
import ai.apologist.errors.InternalServerError;
import ai.apologist.errors.NotFoundError;
import ai.apologist.errors.UnprocessableEntityError;
import ai.apologist.resources.users.requests.AnonymizeUserRequest;
import ai.apologist.resources.users.requests.GetUserRequest;
import ai.apologist.resources.users.requests.ListUserFlagsRequest;
import ai.apologist.resources.users.requests.ListUsersRequest;
import ai.apologist.resources.users.requests.ScrubUserRequest;
import ai.apologist.resources.users.requests.UserUpdateRequest;
import ai.apologist.resources.users.types.AnonymizeUserResponse;
import ai.apologist.resources.users.types.GetUserResponse;
import ai.apologist.resources.users.types.ListUserFlagsResponse;
import ai.apologist.resources.users.types.ListUsersResponse;
import ai.apologist.resources.users.types.ScrubUserResponse;
import ai.apologist.resources.users.types.UpdateUserResponse;
import ai.apologist.types.Error;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawUsersClient {
    protected final ClientOptions clientOptions;

    public AsyncRawUsersClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns a paginated list of users for the agent's team, with applied tags expanded as { id, name } and the persisted responder id.
     */
    public CompletableFuture<AgentClientHttpResponse<ListUsersResponse>> listUsers() {
        return listUsers(ListUsersRequest.builder().build());
    }

    /**
     * Returns a paginated list of users for the agent's team, with applied tags expanded as { id, name } and the persisted responder id.
     */
    public CompletableFuture<AgentClientHttpResponse<ListUsersResponse>> listUsers(RequestOptions requestOptions) {
        return listUsers(ListUsersRequest.builder().build(), requestOptions);
    }

    /**
     * Returns a paginated list of users for the agent's team, with applied tags expanded as { id, name } and the persisted responder id.
     */
    public CompletableFuture<AgentClientHttpResponse<ListUsersResponse>> listUsers(ListUsersRequest request) {
        return listUsers(request, null);
    }

    /**
     * Returns a paginated list of users for the agent's team, with applied tags expanded as { id, name } and the persisted responder id.
     */
    public CompletableFuture<AgentClientHttpResponse<ListUsersResponse>> listUsers(
            ListUsersRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users");
        if (request.getPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getPerPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "per_page", request.getPerPage().get(), false);
        }
        if (request.getExternalId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "external_id", request.getExternalId().get(), false);
        }
        if (request.getTags().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "tags", request.getTags().get(), false);
        }
        if (request.getResponderId().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "responder_id", request.getResponderId().get(), false);
        }
        if (request.getMinTimestamp().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "min_timestamp", request.getMinTimestamp().get(), false);
        }
        if (request.getMaxTimestamp().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "max_timestamp", request.getMaxTimestamp().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<AgentClientHttpResponse<ListUsersResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new AgentClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListUsersResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new AgentClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new AgentClientException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new AgentClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new AgentClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Returns a paginated list of user flag definitions for the agent's team (all columns from user_flags), ordered by id ascending.
     */
    public CompletableFuture<AgentClientHttpResponse<ListUserFlagsResponse>> listUserFlags() {
        return listUserFlags(ListUserFlagsRequest.builder().build());
    }

    /**
     * Returns a paginated list of user flag definitions for the agent's team (all columns from user_flags), ordered by id ascending.
     */
    public CompletableFuture<AgentClientHttpResponse<ListUserFlagsResponse>> listUserFlags(
            RequestOptions requestOptions) {
        return listUserFlags(ListUserFlagsRequest.builder().build(), requestOptions);
    }

    /**
     * Returns a paginated list of user flag definitions for the agent's team (all columns from user_flags), ordered by id ascending.
     */
    public CompletableFuture<AgentClientHttpResponse<ListUserFlagsResponse>> listUserFlags(
            ListUserFlagsRequest request) {
        return listUserFlags(request, null);
    }

    /**
     * Returns a paginated list of user flag definitions for the agent's team (all columns from user_flags), ordered by id ascending.
     */
    public CompletableFuture<AgentClientHttpResponse<ListUserFlagsResponse>> listUserFlags(
            ListUserFlagsRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users/flags");
        if (request.getPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page", request.getPage().get(), false);
        }
        if (request.getPerPage().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "per_page", request.getPerPage().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<AgentClientHttpResponse<ListUserFlagsResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new AgentClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ListUserFlagsResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new AgentClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new AgentClientException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new AgentClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new AgentClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Returns a single user by external id or internal id, with expanded tags and the persisted responder for the agent.
     */
    public CompletableFuture<AgentClientHttpResponse<GetUserResponse>> getUser(String userId) {
        return getUser(userId, GetUserRequest.builder().build());
    }

    /**
     * Returns a single user by external id or internal id, with expanded tags and the persisted responder for the agent.
     */
    public CompletableFuture<AgentClientHttpResponse<GetUserResponse>> getUser(
            String userId, RequestOptions requestOptions) {
        return getUser(userId, GetUserRequest.builder().build(), requestOptions);
    }

    /**
     * Returns a single user by external id or internal id, with expanded tags and the persisted responder for the agent.
     */
    public CompletableFuture<AgentClientHttpResponse<GetUserResponse>> getUser(String userId, GetUserRequest request) {
        return getUser(userId, request, null);
    }

    /**
     * Returns a single user by external id or internal id, with expanded tags and the persisted responder for the agent.
     */
    public CompletableFuture<AgentClientHttpResponse<GetUserResponse>> getUser(
            String userId, GetUserRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(userId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<AgentClientHttpResponse<GetUserResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new AgentClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, GetUserResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new AgentClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new AgentClientException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new AgentClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new AgentClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Updates a user's external_id and/or tags and upserts the persisted responder for the agent. Only provided fields are changed.
     */
    public CompletableFuture<AgentClientHttpResponse<UpdateUserResponse>> updateUser(String userId) {
        return updateUser(userId, UserUpdateRequest.builder().build());
    }

    /**
     * Updates a user's external_id and/or tags and upserts the persisted responder for the agent. Only provided fields are changed.
     */
    public CompletableFuture<AgentClientHttpResponse<UpdateUserResponse>> updateUser(
            String userId, RequestOptions requestOptions) {
        return updateUser(userId, UserUpdateRequest.builder().build(), requestOptions);
    }

    /**
     * Updates a user's external_id and/or tags and upserts the persisted responder for the agent. Only provided fields are changed.
     */
    public CompletableFuture<AgentClientHttpResponse<UpdateUserResponse>> updateUser(
            String userId, UserUpdateRequest request) {
        return updateUser(userId, request, null);
    }

    /**
     * Updates a user's external_id and/or tags and upserts the persisted responder for the agent. Only provided fields are changed.
     */
    public CompletableFuture<AgentClientHttpResponse<UpdateUserResponse>> updateUser(
            String userId, UserUpdateRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(userId);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new AgentClientException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PATCH", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<AgentClientHttpResponse<UpdateUserResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new AgentClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, UpdateUserResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 422:
                                future.completeExceptionally(new UnprocessableEntityError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Error.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new AgentClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new AgentClientException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new AgentClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new AgentClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Replaces this user's message-adjacent text with a placeholder. Conversation rows, identifiers, flags, and analytics identity stay in place. Repeat calls finish leftover rows.
     */
    public CompletableFuture<AgentClientHttpResponse<ScrubUserResponse>> scrubUser(String userId) {
        return scrubUser(userId, ScrubUserRequest.builder().build());
    }

    /**
     * Replaces this user's message-adjacent text with a placeholder. Conversation rows, identifiers, flags, and analytics identity stay in place. Repeat calls finish leftover rows.
     */
    public CompletableFuture<AgentClientHttpResponse<ScrubUserResponse>> scrubUser(
            String userId, RequestOptions requestOptions) {
        return scrubUser(userId, ScrubUserRequest.builder().build(), requestOptions);
    }

    /**
     * Replaces this user's message-adjacent text with a placeholder. Conversation rows, identifiers, flags, and analytics identity stay in place. Repeat calls finish leftover rows.
     */
    public CompletableFuture<AgentClientHttpResponse<ScrubUserResponse>> scrubUser(
            String userId, ScrubUserRequest request) {
        return scrubUser(userId, request, null);
    }

    /**
     * Replaces this user's message-adjacent text with a placeholder. Conversation rows, identifiers, flags, and analytics identity stay in place. Repeat calls finish leftover rows.
     */
    public CompletableFuture<AgentClientHttpResponse<ScrubUserResponse>> scrubUser(
            String userId, ScrubUserRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(userId)
                .addPathSegments("scrub");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", RequestBody.create("", null))
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<AgentClientHttpResponse<ScrubUserResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new AgentClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ScrubUserResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new AgentClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new AgentClientException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new AgentClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new AgentClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    /**
     * Redacts detected personal data in this user's message-adjacent text with regex, then an optional hosted redaction service when the Agent has that option on. Conversation rows, identifiers, flags, and analytics identity stay in place. Repeat calls finish leftover rows and skip text that is already redacted.
     */
    public CompletableFuture<AgentClientHttpResponse<AnonymizeUserResponse>> anonymizeUser(String userId) {
        return anonymizeUser(userId, AnonymizeUserRequest.builder().build());
    }

    /**
     * Redacts detected personal data in this user's message-adjacent text with regex, then an optional hosted redaction service when the Agent has that option on. Conversation rows, identifiers, flags, and analytics identity stay in place. Repeat calls finish leftover rows and skip text that is already redacted.
     */
    public CompletableFuture<AgentClientHttpResponse<AnonymizeUserResponse>> anonymizeUser(
            String userId, RequestOptions requestOptions) {
        return anonymizeUser(userId, AnonymizeUserRequest.builder().build(), requestOptions);
    }

    /**
     * Redacts detected personal data in this user's message-adjacent text with regex, then an optional hosted redaction service when the Agent has that option on. Conversation rows, identifiers, flags, and analytics identity stay in place. Repeat calls finish leftover rows and skip text that is already redacted.
     */
    public CompletableFuture<AgentClientHttpResponse<AnonymizeUserResponse>> anonymizeUser(
            String userId, AnonymizeUserRequest request) {
        return anonymizeUser(userId, request, null);
    }

    /**
     * Redacts detected personal data in this user's message-adjacent text with regex, then an optional hosted redaction service when the Agent has that option on. Conversation rows, identifiers, flags, and analytics identity stay in place. Repeat calls finish leftover rows and skip text that is already redacted.
     */
    public CompletableFuture<AgentClientHttpResponse<AnonymizeUserResponse>> anonymizeUser(
            String userId, AnonymizeUserRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("users")
                .addPathSegment(userId)
                .addPathSegments("anonymize");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", RequestBody.create("", null))
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        CompletableFuture<AgentClientHttpResponse<AnonymizeUserResponse>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new AgentClientHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, AnonymizeUserResponse.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new AgentClientApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (JsonProcessingException e) {
                    future.completeExceptionally(
                            new AgentClientException("Failed to deserialize response: " + e.getMessage(), e));
                } catch (IOException e) {
                    future.completeExceptionally(new AgentClientException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new AgentClientException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
