/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.resources.agent;

import ai.apologist.core.ClientOptions;
import ai.apologist.core.RequestOptions;
import ai.apologist.resources.agent.types.PauseAgentResponse;
import ai.apologist.resources.agent.types.ResumeAgentResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncAgentClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawAgentClient rawClient;

    public AsyncAgentClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawAgentClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawAgentClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Pauses the agent globally and fans out pause transition messages to open conversations. Requires an API key.
     */
    public CompletableFuture<PauseAgentResponse> pauseAgent() {
        return this.rawClient.pauseAgent().thenApply(response -> response.body());
    }

    /**
     * Pauses the agent globally and fans out pause transition messages to open conversations. Requires an API key.
     */
    public CompletableFuture<PauseAgentResponse> pauseAgent(RequestOptions requestOptions) {
        return this.rawClient.pauseAgent(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Resumes the agent globally and fans out resume transition messages to open conversations. Requires an API key.
     */
    public CompletableFuture<ResumeAgentResponse> resumeAgent() {
        return this.rawClient.resumeAgent().thenApply(response -> response.body());
    }

    /**
     * Resumes the agent globally and fans out resume transition messages to open conversations. Requires an API key.
     */
    public CompletableFuture<ResumeAgentResponse> resumeAgent(RequestOptions requestOptions) {
        return this.rawClient.resumeAgent(requestOptions).thenApply(response -> response.body());
    }
}
