/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.resources.agent;

import ai.apologist.core.AgentClientApiException;
import ai.apologist.core.AgentClientException;
import ai.apologist.core.AgentClientHttpResponse;
import ai.apologist.core.ClientOptions;
import ai.apologist.core.ObjectMappers;
import ai.apologist.core.RequestOptions;
import ai.apologist.core.RetryInterceptor;
import ai.apologist.errors.ForbiddenError;
import ai.apologist.errors.InternalServerError;
import ai.apologist.resources.agent.types.PauseAgentResponse;
import ai.apologist.resources.agent.types.ResumeAgentResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawAgentClient {
    protected final ClientOptions clientOptions;

    public RawAgentClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Pauses the agent globally and fans out pause transition messages to open conversations. Requires an API key.
     */
    public AgentClientHttpResponse<PauseAgentResponse> pauseAgent() {
        return pauseAgent(null);
    }

    /**
     * Pauses the agent globally and fans out pause transition messages to open conversations. Requires an API key.
     */
    public AgentClientHttpResponse<PauseAgentResponse> pauseAgent(RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("pause");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", RequestBody.create("", null))
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new AgentClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, PauseAgentResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new AgentClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new AgentClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new AgentClientException("Network error executing HTTP request", e);
        }
    }

    /**
     * Resumes the agent globally and fans out resume transition messages to open conversations. Requires an API key.
     */
    public AgentClientHttpResponse<ResumeAgentResponse> resumeAgent() {
        return resumeAgent(null);
    }

    /**
     * Resumes the agent globally and fans out resume transition messages to open conversations. Requires an API key.
     */
    public AgentClientHttpResponse<ResumeAgentResponse> resumeAgent(RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("resume");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", RequestBody.create("", null))
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest
                    .newBuilder()
                    .tag(
                            RetryInterceptor.MaxRetriesOverride.class,
                            new RetryInterceptor.MaxRetriesOverride(
                                    requestOptions.getMaxRetries().get()))
                    .build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new AgentClientHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ResumeAgentResponse.class), response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, Object.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new AgentClientApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (JsonProcessingException e) {
            throw new AgentClientException("Failed to deserialize response: " + e.getMessage(), e);
        } catch (IOException e) {
            throw new AgentClientException("Network error executing HTTP request", e);
        }
    }
}
