/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.ai.api.resources.channels.requests;

import com.apologist.ai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ReceiveDiscordInteractionRequest.Builder.class)
public final class ReceiveDiscordInteractionRequest {
    private final String signatureEd25519;

    private final String signatureTimestamp;

    private final Map<String, Object> body;

    private final Map<String, Object> additionalProperties;

    private ReceiveDiscordInteractionRequest(
            String signatureEd25519,
            String signatureTimestamp,
            Map<String, Object> body,
            Map<String, Object> additionalProperties) {
        this.signatureEd25519 = signatureEd25519;
        this.signatureTimestamp = signatureTimestamp;
        this.body = body;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Discord request signature (hex).
     */
    @JsonIgnore
    public String getSignatureEd25519() {
        return signatureEd25519;
    }

    /**
     * @return Discord request timestamp.
     */
    @JsonIgnore
    public String getSignatureTimestamp() {
        return signatureTimestamp;
    }

    /**
     * @return Discord interaction payload.
     */
    @JsonProperty("body")
    public Map<String, Object> getBody() {
        return body;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ReceiveDiscordInteractionRequest && equalTo((ReceiveDiscordInteractionRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ReceiveDiscordInteractionRequest other) {
        return signatureEd25519.equals(other.signatureEd25519)
                && signatureTimestamp.equals(other.signatureTimestamp)
                && body.equals(other.body);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.signatureEd25519, this.signatureTimestamp, this.body);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SignatureEd25519Stage builder() {
        return new Builder();
    }

    public interface SignatureEd25519Stage {
        /**
         * <p>Discord request signature (hex).</p>
         */
        SignatureTimestampStage signatureEd25519(@NotNull String signatureEd25519);

        Builder from(ReceiveDiscordInteractionRequest other);
    }

    public interface SignatureTimestampStage {
        /**
         * <p>Discord request timestamp.</p>
         */
        _FinalStage signatureTimestamp(@NotNull String signatureTimestamp);
    }

    public interface _FinalStage {
        ReceiveDiscordInteractionRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Discord interaction payload.</p>
         */
        _FinalStage body(Map<String, Object> body);

        _FinalStage putAllBody(Map<String, Object> body);

        _FinalStage body(String key, Object value);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SignatureEd25519Stage, SignatureTimestampStage, _FinalStage {
        private String signatureEd25519;

        private String signatureTimestamp;

        private Map<String, Object> body = new LinkedHashMap<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ReceiveDiscordInteractionRequest other) {
            signatureEd25519(other.getSignatureEd25519());
            signatureTimestamp(other.getSignatureTimestamp());
            body(other.getBody());
            return this;
        }

        /**
         * <p>Discord request signature (hex).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public SignatureTimestampStage signatureEd25519(@NotNull String signatureEd25519) {
            this.signatureEd25519 = Objects.requireNonNull(signatureEd25519, "signatureEd25519 must not be null");
            return this;
        }

        /**
         * <p>Discord request timestamp.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage signatureTimestamp(@NotNull String signatureTimestamp) {
            this.signatureTimestamp = Objects.requireNonNull(signatureTimestamp, "signatureTimestamp must not be null");
            return this;
        }

        /**
         * <p>Discord interaction payload.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage body(String key, Object value) {
            this.body.put(key, value);
            return this;
        }

        /**
         * <p>Discord interaction payload.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage putAllBody(Map<String, Object> body) {
            if (body != null) {
                this.body.putAll(body);
            }
            return this;
        }

        /**
         * <p>Discord interaction payload.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "body", nulls = Nulls.SKIP)
        public _FinalStage body(Map<String, Object> body) {
            this.body.clear();
            if (body != null) {
                this.body.putAll(body);
            }
            return this;
        }

        @java.lang.Override
        public ReceiveDiscordInteractionRequest build() {
            return new ReceiveDiscordInteractionRequest(
                    signatureEd25519, signatureTimestamp, body, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
