/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.ai.api.resources.users.requests;

import com.apologist.ai.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListUsersRequest.Builder.class)
public final class ListUsersRequest {
    private final Optional<Integer> page;

    private final Optional<Integer> perPage;

    private final Optional<String> externalId;

    private final Optional<String> tags;

    private final Optional<String> responderId;

    private final Optional<String> minTimestamp;

    private final Optional<String> maxTimestamp;

    private final Map<String, Object> additionalProperties;

    private ListUsersRequest(
            Optional<Integer> page,
            Optional<Integer> perPage,
            Optional<String> externalId,
            Optional<String> tags,
            Optional<String> responderId,
            Optional<String> minTimestamp,
            Optional<String> maxTimestamp,
            Map<String, Object> additionalProperties) {
        this.page = page;
        this.perPage = perPage;
        this.externalId = externalId;
        this.tags = tags;
        this.responderId = responderId;
        this.minTimestamp = minTimestamp;
        this.maxTimestamp = maxTimestamp;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("page")
    public Optional<Integer> getPage() {
        return page;
    }

    /**
     * @return Results per page (clamped to 100).
     */
    @JsonProperty("per_page")
    public Optional<Integer> getPerPage() {
        return perPage;
    }

    @JsonProperty("external_id")
    public Optional<String> getExternalId() {
        return externalId;
    }

    /**
     * @return Comma-separated tag ids.
     */
    @JsonProperty("tags")
    public Optional<String> getTags() {
        return tags;
    }

    @JsonProperty("responder_id")
    public Optional<String> getResponderId() {
        return responderId;
    }

    @JsonProperty("min_timestamp")
    public Optional<String> getMinTimestamp() {
        return minTimestamp;
    }

    @JsonProperty("max_timestamp")
    public Optional<String> getMaxTimestamp() {
        return maxTimestamp;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListUsersRequest && equalTo((ListUsersRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListUsersRequest other) {
        return page.equals(other.page)
                && perPage.equals(other.perPage)
                && externalId.equals(other.externalId)
                && tags.equals(other.tags)
                && responderId.equals(other.responderId)
                && minTimestamp.equals(other.minTimestamp)
                && maxTimestamp.equals(other.maxTimestamp);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.page,
                this.perPage,
                this.externalId,
                this.tags,
                this.responderId,
                this.minTimestamp,
                this.maxTimestamp);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Integer> page = Optional.empty();

        private Optional<Integer> perPage = Optional.empty();

        private Optional<String> externalId = Optional.empty();

        private Optional<String> tags = Optional.empty();

        private Optional<String> responderId = Optional.empty();

        private Optional<String> minTimestamp = Optional.empty();

        private Optional<String> maxTimestamp = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ListUsersRequest other) {
            page(other.getPage());
            perPage(other.getPerPage());
            externalId(other.getExternalId());
            tags(other.getTags());
            responderId(other.getResponderId());
            minTimestamp(other.getMinTimestamp());
            maxTimestamp(other.getMaxTimestamp());
            return this;
        }

        @JsonSetter(value = "page", nulls = Nulls.SKIP)
        public Builder page(Optional<Integer> page) {
            this.page = page;
            return this;
        }

        public Builder page(Integer page) {
            this.page = Optional.ofNullable(page);
            return this;
        }

        /**
         * <p>Results per page (clamped to 100).</p>
         */
        @JsonSetter(value = "per_page", nulls = Nulls.SKIP)
        public Builder perPage(Optional<Integer> perPage) {
            this.perPage = perPage;
            return this;
        }

        public Builder perPage(Integer perPage) {
            this.perPage = Optional.ofNullable(perPage);
            return this;
        }

        @JsonSetter(value = "external_id", nulls = Nulls.SKIP)
        public Builder externalId(Optional<String> externalId) {
            this.externalId = externalId;
            return this;
        }

        public Builder externalId(String externalId) {
            this.externalId = Optional.ofNullable(externalId);
            return this;
        }

        /**
         * <p>Comma-separated tag ids.</p>
         */
        @JsonSetter(value = "tags", nulls = Nulls.SKIP)
        public Builder tags(Optional<String> tags) {
            this.tags = tags;
            return this;
        }

        public Builder tags(String tags) {
            this.tags = Optional.ofNullable(tags);
            return this;
        }

        @JsonSetter(value = "responder_id", nulls = Nulls.SKIP)
        public Builder responderId(Optional<String> responderId) {
            this.responderId = responderId;
            return this;
        }

        public Builder responderId(String responderId) {
            this.responderId = Optional.ofNullable(responderId);
            return this;
        }

        @JsonSetter(value = "min_timestamp", nulls = Nulls.SKIP)
        public Builder minTimestamp(Optional<String> minTimestamp) {
            this.minTimestamp = minTimestamp;
            return this;
        }

        public Builder minTimestamp(String minTimestamp) {
            this.minTimestamp = Optional.ofNullable(minTimestamp);
            return this;
        }

        @JsonSetter(value = "max_timestamp", nulls = Nulls.SKIP)
        public Builder maxTimestamp(Optional<String> maxTimestamp) {
            this.maxTimestamp = maxTimestamp;
            return this;
        }

        public Builder maxTimestamp(String maxTimestamp) {
            this.maxTimestamp = Optional.ofNullable(maxTimestamp);
            return this;
        }

        public ListUsersRequest build() {
            return new ListUsersRequest(
                    page, perPage, externalId, tags, responderId, minTimestamp, maxTimestamp, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
