/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class ApologistAgentClientException extends RuntimeException {
    public ApologistAgentClientException(String message) {
        super(message);
    }

    public ApologistAgentClientException(String message, Exception e) {
        super(message, e);
    }
}
