/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.resources.channels;

import ai.apologist.core.ClientOptions;
import ai.apologist.core.RequestOptions;
import ai.apologist.resources.channels.requests.GetDiscordChannelStatusRequest;
import ai.apologist.resources.channels.requests.GetInstagramPrivacyPolicyRequest;
import ai.apologist.resources.channels.requests.ReceiveDiscordInteractionRequest;
import ai.apologist.resources.channels.requests.ReceiveFacebookMessageRequest;
import ai.apologist.resources.channels.requests.ReceiveTelegramUpdateRequest;
import ai.apologist.resources.channels.requests.ReceiveTwilioMessageRequest;
import ai.apologist.resources.channels.requests.VerifyFacebookWebhookRequest;
import ai.apologist.resources.channels.types.GetDiscordChannelStatusResponse;

public class ChannelsClient {
    protected final ClientOptions clientOptions;

    private final RawChannelsClient rawClient;

    public ChannelsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawChannelsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawChannelsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns the status of the Discord channel. Used as a lightweight health/verification endpoint.
     */
    public GetDiscordChannelStatusResponse getDiscordChannelStatus(String id) {
        return this.rawClient.getDiscordChannelStatus(id).body();
    }

    /**
     * Returns the status of the Discord channel. Used as a lightweight health/verification endpoint.
     */
    public GetDiscordChannelStatusResponse getDiscordChannelStatus(String id, RequestOptions requestOptions) {
        return this.rawClient.getDiscordChannelStatus(id, requestOptions).body();
    }

    /**
     * Returns the status of the Discord channel. Used as a lightweight health/verification endpoint.
     */
    public GetDiscordChannelStatusResponse getDiscordChannelStatus(String id, GetDiscordChannelStatusRequest request) {
        return this.rawClient.getDiscordChannelStatus(id, request).body();
    }

    /**
     * Returns the status of the Discord channel. Used as a lightweight health/verification endpoint.
     */
    public GetDiscordChannelStatusResponse getDiscordChannelStatus(
            String id, GetDiscordChannelStatusRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getDiscordChannelStatus(id, request, requestOptions)
                .body();
    }

    /**
     * Receives Discord interaction callbacks for the channel. Requests are verified via Ed25519 signature headers; unsigned or invalid requests are rejected. Payload shape is defined by Discord.
     */
    public void receiveDiscordInteraction(String id, ReceiveDiscordInteractionRequest request) {
        this.rawClient.receiveDiscordInteraction(id, request).body();
    }

    /**
     * Receives Discord interaction callbacks for the channel. Requests are verified via Ed25519 signature headers; unsigned or invalid requests are rejected. Payload shape is defined by Discord.
     */
    public void receiveDiscordInteraction(
            String id, ReceiveDiscordInteractionRequest request, RequestOptions requestOptions) {
        this.rawClient.receiveDiscordInteraction(id, request, requestOptions).body();
    }

    /**
     * Handles the Meta webhook verification handshake, echoing <code>hub.challenge</code> when <code>hub.verify_token</code> matches the channel's configured token.
     */
    public String verifyFacebookWebhook(String id, VerifyFacebookWebhookRequest request) {
        return this.rawClient.verifyFacebookWebhook(id, request).body();
    }

    /**
     * Handles the Meta webhook verification handshake, echoing <code>hub.challenge</code> when <code>hub.verify_token</code> matches the channel's configured token.
     */
    public String verifyFacebookWebhook(
            String id, VerifyFacebookWebhookRequest request, RequestOptions requestOptions) {
        return this.rawClient.verifyFacebookWebhook(id, request, requestOptions).body();
    }

    /**
     * Receives Facebook/Messenger (and Instagram-style) message events for the channel. Payload shape is defined by Meta.
     */
    public void receiveFacebookMessage(String id, ReceiveFacebookMessageRequest request) {
        this.rawClient.receiveFacebookMessage(id, request).body();
    }

    /**
     * Receives Facebook/Messenger (and Instagram-style) message events for the channel. Payload shape is defined by Meta.
     */
    public void receiveFacebookMessage(
            String id, ReceiveFacebookMessageRequest request, RequestOptions requestOptions) {
        this.rawClient.receiveFacebookMessage(id, request, requestOptions).body();
    }

    /**
     * Returns a static HTML privacy policy page for the Instagram integration.
     */
    public String getInstagramPrivacyPolicy(String id) {
        return this.rawClient.getInstagramPrivacyPolicy(id).body();
    }

    /**
     * Returns a static HTML privacy policy page for the Instagram integration.
     */
    public String getInstagramPrivacyPolicy(String id, RequestOptions requestOptions) {
        return this.rawClient.getInstagramPrivacyPolicy(id, requestOptions).body();
    }

    /**
     * Returns a static HTML privacy policy page for the Instagram integration.
     */
    public String getInstagramPrivacyPolicy(String id, GetInstagramPrivacyPolicyRequest request) {
        return this.rawClient.getInstagramPrivacyPolicy(id, request).body();
    }

    /**
     * Returns a static HTML privacy policy page for the Instagram integration.
     */
    public String getInstagramPrivacyPolicy(
            String id, GetInstagramPrivacyPolicyRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getInstagramPrivacyPolicy(id, request, requestOptions)
                .body();
    }

    /**
     * Receives Telegram bot update events for the channel. Non-message updates are acknowledged and ignored. Payload shape is defined by Telegram.
     */
    public void receiveTelegramUpdate(String id, ReceiveTelegramUpdateRequest request) {
        this.rawClient.receiveTelegramUpdate(id, request).body();
    }

    /**
     * Receives Telegram bot update events for the channel. Non-message updates are acknowledged and ignored. Payload shape is defined by Telegram.
     */
    public void receiveTelegramUpdate(String id, ReceiveTelegramUpdateRequest request, RequestOptions requestOptions) {
        this.rawClient.receiveTelegramUpdate(id, request, requestOptions).body();
    }

    /**
     * Receives inbound Twilio messages for the channel as form-encoded data. Payload fields are defined by Twilio.
     */
    public void receiveTwilioMessage(String id) {
        this.rawClient.receiveTwilioMessage(id).body();
    }

    /**
     * Receives inbound Twilio messages for the channel as form-encoded data. Payload fields are defined by Twilio.
     */
    public void receiveTwilioMessage(String id, RequestOptions requestOptions) {
        this.rawClient.receiveTwilioMessage(id, requestOptions).body();
    }

    /**
     * Receives inbound Twilio messages for the channel as form-encoded data. Payload fields are defined by Twilio.
     */
    public void receiveTwilioMessage(String id, ReceiveTwilioMessageRequest request) {
        this.rawClient.receiveTwilioMessage(id, request).body();
    }

    /**
     * Receives inbound Twilio messages for the channel as form-encoded data. Payload fields are defined by Twilio.
     */
    public void receiveTwilioMessage(String id, ReceiveTwilioMessageRequest request, RequestOptions requestOptions) {
        this.rawClient.receiveTwilioMessage(id, request, requestOptions).body();
    }
}
