/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist;

import com.apologist.core.ClientOptions;
import com.apologist.core.Suppliers;
import com.apologist.resources.benchmarks.BenchmarksClient;
import com.apologist.resources.channels.ChannelsClient;
import com.apologist.resources.chat.ChatClient;
import com.apologist.resources.corpus.CorpusClient;
import com.apologist.resources.ctas.CtAsClient;
import com.apologist.resources.evaluators.EvaluatorsClient;
import com.apologist.resources.shares.SharesClient;
import com.apologist.resources.users.UsersClient;
import java.util.function.Supplier;

public class ApologistAgentClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<ChatClient> chatClient;

    protected final Supplier<CorpusClient> corpusClient;

    protected final Supplier<EvaluatorsClient> evaluatorsClient;

    protected final Supplier<CtAsClient> ctAsClient;

    protected final Supplier<UsersClient> usersClient;

    protected final Supplier<BenchmarksClient> benchmarksClient;

    protected final Supplier<ChannelsClient> channelsClient;

    protected final Supplier<SharesClient> sharesClient;

    public ApologistAgentClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.chatClient = Suppliers.memoize(() -> new ChatClient(clientOptions));
        this.corpusClient = Suppliers.memoize(() -> new CorpusClient(clientOptions));
        this.evaluatorsClient = Suppliers.memoize(() -> new EvaluatorsClient(clientOptions));
        this.ctAsClient = Suppliers.memoize(() -> new CtAsClient(clientOptions));
        this.usersClient = Suppliers.memoize(() -> new UsersClient(clientOptions));
        this.benchmarksClient = Suppliers.memoize(() -> new BenchmarksClient(clientOptions));
        this.channelsClient = Suppliers.memoize(() -> new ChannelsClient(clientOptions));
        this.sharesClient = Suppliers.memoize(() -> new SharesClient(clientOptions));
    }

    public ChatClient chat() {
        return this.chatClient.get();
    }

    public CorpusClient corpus() {
        return this.corpusClient.get();
    }

    public EvaluatorsClient evaluators() {
        return this.evaluatorsClient.get();
    }

    public CtAsClient ctAs() {
        return this.ctAsClient.get();
    }

    public UsersClient users() {
        return this.usersClient.get();
    }

    public BenchmarksClient benchmarks() {
        return this.benchmarksClient.get();
    }

    public ChannelsClient channels() {
        return this.channelsClient.get();
    }

    public SharesClient shares() {
        return this.sharesClient.get();
    }

    public static ApologistAgentClientBuilder builder() {
        return new ApologistAgentClientBuilder();
    }
}
