/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist;

import com.apologist.core.ClientOptions;
import com.apologist.core.Suppliers;
import com.apologist.resources.benchmarks.AsyncBenchmarksClient;
import com.apologist.resources.channels.AsyncChannelsClient;
import com.apologist.resources.chat.AsyncChatClient;
import com.apologist.resources.corpus.AsyncCorpusClient;
import com.apologist.resources.ctas.AsyncCtAsClient;
import com.apologist.resources.evaluators.AsyncEvaluatorsClient;
import com.apologist.resources.shares.AsyncSharesClient;
import com.apologist.resources.users.AsyncUsersClient;
import java.util.function.Supplier;

public class AsyncApologistAgentClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncChatClient> chatClient;

    protected final Supplier<AsyncCorpusClient> corpusClient;

    protected final Supplier<AsyncEvaluatorsClient> evaluatorsClient;

    protected final Supplier<AsyncCtAsClient> ctAsClient;

    protected final Supplier<AsyncUsersClient> usersClient;

    protected final Supplier<AsyncBenchmarksClient> benchmarksClient;

    protected final Supplier<AsyncChannelsClient> channelsClient;

    protected final Supplier<AsyncSharesClient> sharesClient;

    public AsyncApologistAgentClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.chatClient = Suppliers.memoize(() -> new AsyncChatClient(clientOptions));
        this.corpusClient = Suppliers.memoize(() -> new AsyncCorpusClient(clientOptions));
        this.evaluatorsClient = Suppliers.memoize(() -> new AsyncEvaluatorsClient(clientOptions));
        this.ctAsClient = Suppliers.memoize(() -> new AsyncCtAsClient(clientOptions));
        this.usersClient = Suppliers.memoize(() -> new AsyncUsersClient(clientOptions));
        this.benchmarksClient = Suppliers.memoize(() -> new AsyncBenchmarksClient(clientOptions));
        this.channelsClient = Suppliers.memoize(() -> new AsyncChannelsClient(clientOptions));
        this.sharesClient = Suppliers.memoize(() -> new AsyncSharesClient(clientOptions));
    }

    public AsyncChatClient chat() {
        return this.chatClient.get();
    }

    public AsyncCorpusClient corpus() {
        return this.corpusClient.get();
    }

    public AsyncEvaluatorsClient evaluators() {
        return this.evaluatorsClient.get();
    }

    public AsyncCtAsClient ctAs() {
        return this.ctAsClient.get();
    }

    public AsyncUsersClient users() {
        return this.usersClient.get();
    }

    public AsyncBenchmarksClient benchmarks() {
        return this.benchmarksClient.get();
    }

    public AsyncChannelsClient channels() {
        return this.channelsClient.get();
    }

    public AsyncSharesClient shares() {
        return this.sharesClient.get();
    }

    public static AsyncApologistAgentClientBuilder builder() {
        return new AsyncApologistAgentClientBuilder();
    }
}
