/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.ai.api.core;

/**
 * This class serves as the base exception for all errors in the SDK.
 */
public class ApologistAiApiException extends RuntimeException {
    public ApologistAiApiException(String message) {
        super(message);
    }

    public ApologistAiApiException(String message, Exception e) {
        super(message, e);
    }
}
