/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.apologist.api.resources.ctas.requests;

import com.apologist.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CtaClickRequest.Builder.class)
public final class CtaClickRequest {
    private final String promptId;

    private final Map<String, Object> additionalProperties;

    private CtaClickRequest(String promptId, Map<String, Object> additionalProperties) {
        this.promptId = promptId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("prompt_id")
    public String getPromptId() {
        return promptId;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CtaClickRequest && equalTo((CtaClickRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CtaClickRequest other) {
        return promptId.equals(other.promptId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.promptId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static PromptIdStage builder() {
        return new Builder();
    }

    public interface PromptIdStage {
        _FinalStage promptId(@NotNull String promptId);

        Builder from(CtaClickRequest other);
    }

    public interface _FinalStage {
        CtaClickRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements PromptIdStage, _FinalStage {
        private String promptId;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CtaClickRequest other) {
            promptId(other.getPromptId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("prompt_id")
        public _FinalStage promptId(@NotNull String promptId) {
            this.promptId = Objects.requireNonNull(promptId, "promptId must not be null");
            return this;
        }

        @java.lang.Override
        public CtaClickRequest build() {
            return new CtaClickRequest(promptId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
