/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.resources.channels.requests;

import ai.apologist.core.ObjectMappers;
import ai.apologist.resources.channels.types.VerifyFacebookWebhookRequestHubMode;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = VerifyFacebookWebhookRequest.Builder.class)
public final class VerifyFacebookWebhookRequest {
    private final VerifyFacebookWebhookRequestHubMode hubMode;

    private final String hubVerifyToken;

    private final Optional<String> hubChallenge;

    private final Map<String, Object> additionalProperties;

    private VerifyFacebookWebhookRequest(
            VerifyFacebookWebhookRequestHubMode hubMode,
            String hubVerifyToken,
            Optional<String> hubChallenge,
            Map<String, Object> additionalProperties) {
        this.hubMode = hubMode;
        this.hubVerifyToken = hubVerifyToken;
        this.hubChallenge = hubChallenge;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("hub.mode")
    public VerifyFacebookWebhookRequestHubMode getHubMode() {
        return hubMode;
    }

    @JsonProperty("hub.verify_token")
    public String getHubVerifyToken() {
        return hubVerifyToken;
    }

    @JsonProperty("hub.challenge")
    public Optional<String> getHubChallenge() {
        return hubChallenge;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof VerifyFacebookWebhookRequest && equalTo((VerifyFacebookWebhookRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(VerifyFacebookWebhookRequest other) {
        return hubMode.equals(other.hubMode)
                && hubVerifyToken.equals(other.hubVerifyToken)
                && hubChallenge.equals(other.hubChallenge);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.hubMode, this.hubVerifyToken, this.hubChallenge);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static HubModeStage builder() {
        return new Builder();
    }

    public interface HubModeStage {
        HubVerifyTokenStage hubMode(@NotNull VerifyFacebookWebhookRequestHubMode hubMode);

        Builder from(VerifyFacebookWebhookRequest other);
    }

    public interface HubVerifyTokenStage {
        _FinalStage hubVerifyToken(@NotNull String hubVerifyToken);
    }

    public interface _FinalStage {
        VerifyFacebookWebhookRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage hubChallenge(Optional<String> hubChallenge);

        _FinalStage hubChallenge(String hubChallenge);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements HubModeStage, HubVerifyTokenStage, _FinalStage {
        private VerifyFacebookWebhookRequestHubMode hubMode;

        private String hubVerifyToken;

        private Optional<String> hubChallenge = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(VerifyFacebookWebhookRequest other) {
            hubMode(other.getHubMode());
            hubVerifyToken(other.getHubVerifyToken());
            hubChallenge(other.getHubChallenge());
            return this;
        }

        @java.lang.Override
        @JsonSetter("hub.mode")
        public HubVerifyTokenStage hubMode(@NotNull VerifyFacebookWebhookRequestHubMode hubMode) {
            this.hubMode = Objects.requireNonNull(hubMode, "hubMode must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("hub.verify_token")
        public _FinalStage hubVerifyToken(@NotNull String hubVerifyToken) {
            this.hubVerifyToken = Objects.requireNonNull(hubVerifyToken, "hubVerifyToken must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage hubChallenge(String hubChallenge) {
            this.hubChallenge = Optional.ofNullable(hubChallenge);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "hub.challenge", nulls = Nulls.SKIP)
        public _FinalStage hubChallenge(Optional<String> hubChallenge) {
            this.hubChallenge = hubChallenge;
            return this;
        }

        @java.lang.Override
        public VerifyFacebookWebhookRequest build() {
            return new VerifyFacebookWebhookRequest(hubMode, hubVerifyToken, hubChallenge, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
