/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.resources.conversations;

import ai.apologist.core.ClientOptions;
import ai.apologist.core.RequestOptions;
import ai.apologist.resources.conversations.requests.GetConversationRequest;
import ai.apologist.resources.conversations.requests.ListConversationsRequest;
import ai.apologist.resources.conversations.requests.PauseConversationRequest;
import ai.apologist.resources.conversations.requests.ResumeConversationRequest;
import ai.apologist.resources.conversations.types.GetConversationResponse;
import ai.apologist.resources.conversations.types.ListConversationsResponse;
import ai.apologist.resources.conversations.types.PauseConversationResponse;
import ai.apologist.resources.conversations.types.ResumeConversationResponse;
import java.util.concurrent.CompletableFuture;

public class AsyncConversationsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawConversationsClient rawClient;

    public AsyncConversationsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawConversationsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawConversationsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns a paginated list of conversations for the requesting agent, newest first.
     */
    public CompletableFuture<ListConversationsResponse> listConversations() {
        return this.rawClient.listConversations().thenApply(response -> response.body());
    }

    /**
     * Returns a paginated list of conversations for the requesting agent, newest first.
     */
    public CompletableFuture<ListConversationsResponse> listConversations(RequestOptions requestOptions) {
        return this.rawClient.listConversations(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a paginated list of conversations for the requesting agent, newest first.
     */
    public CompletableFuture<ListConversationsResponse> listConversations(ListConversationsRequest request) {
        return this.rawClient.listConversations(request).thenApply(response -> response.body());
    }

    /**
     * Returns a paginated list of conversations for the requesting agent, newest first.
     */
    public CompletableFuture<ListConversationsResponse> listConversations(
            ListConversationsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listConversations(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a single conversation by internal UUID or team-scoped external id.
     */
    public CompletableFuture<GetConversationResponse> getConversation(String id) {
        return this.rawClient.getConversation(id).thenApply(response -> response.body());
    }

    /**
     * Returns a single conversation by internal UUID or team-scoped external id.
     */
    public CompletableFuture<GetConversationResponse> getConversation(String id, RequestOptions requestOptions) {
        return this.rawClient.getConversation(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a single conversation by internal UUID or team-scoped external id.
     */
    public CompletableFuture<GetConversationResponse> getConversation(String id, GetConversationRequest request) {
        return this.rawClient.getConversation(id, request).thenApply(response -> response.body());
    }

    /**
     * Returns a single conversation by internal UUID or team-scoped external id.
     */
    public CompletableFuture<GetConversationResponse> getConversation(
            String id, GetConversationRequest request, RequestOptions requestOptions) {
        return this.rawClient.getConversation(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Pauses the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public CompletableFuture<PauseConversationResponse> pauseConversation(String id) {
        return this.rawClient.pauseConversation(id).thenApply(response -> response.body());
    }

    /**
     * Pauses the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public CompletableFuture<PauseConversationResponse> pauseConversation(String id, RequestOptions requestOptions) {
        return this.rawClient.pauseConversation(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Pauses the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public CompletableFuture<PauseConversationResponse> pauseConversation(String id, PauseConversationRequest request) {
        return this.rawClient.pauseConversation(id, request).thenApply(response -> response.body());
    }

    /**
     * Pauses the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public CompletableFuture<PauseConversationResponse> pauseConversation(
            String id, PauseConversationRequest request, RequestOptions requestOptions) {
        return this.rawClient.pauseConversation(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Resumes the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public CompletableFuture<ResumeConversationResponse> resumeConversation(String id) {
        return this.rawClient.resumeConversation(id).thenApply(response -> response.body());
    }

    /**
     * Resumes the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public CompletableFuture<ResumeConversationResponse> resumeConversation(String id, RequestOptions requestOptions) {
        return this.rawClient.resumeConversation(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Resumes the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public CompletableFuture<ResumeConversationResponse> resumeConversation(
            String id, ResumeConversationRequest request) {
        return this.rawClient.resumeConversation(id, request).thenApply(response -> response.body());
    }

    /**
     * Resumes the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public CompletableFuture<ResumeConversationResponse> resumeConversation(
            String id, ResumeConversationRequest request, RequestOptions requestOptions) {
        return this.rawClient.resumeConversation(id, request, requestOptions).thenApply(response -> response.body());
    }
}
