/**
 * This file was auto-generated by Fern from our API Definition.
 */
package ai.apologist.resources.conversations;

import ai.apologist.core.ClientOptions;
import ai.apologist.core.RequestOptions;
import ai.apologist.resources.conversations.requests.GetConversationRequest;
import ai.apologist.resources.conversations.requests.ListConversationsRequest;
import ai.apologist.resources.conversations.requests.PauseConversationRequest;
import ai.apologist.resources.conversations.requests.ResumeConversationRequest;
import ai.apologist.resources.conversations.types.GetConversationResponse;
import ai.apologist.resources.conversations.types.ListConversationsResponse;
import ai.apologist.resources.conversations.types.PauseConversationResponse;
import ai.apologist.resources.conversations.types.ResumeConversationResponse;

public class ConversationsClient {
    protected final ClientOptions clientOptions;

    private final RawConversationsClient rawClient;

    public ConversationsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawConversationsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawConversationsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns a paginated list of conversations for the requesting agent, newest first.
     */
    public ListConversationsResponse listConversations() {
        return this.rawClient.listConversations().body();
    }

    /**
     * Returns a paginated list of conversations for the requesting agent, newest first.
     */
    public ListConversationsResponse listConversations(RequestOptions requestOptions) {
        return this.rawClient.listConversations(requestOptions).body();
    }

    /**
     * Returns a paginated list of conversations for the requesting agent, newest first.
     */
    public ListConversationsResponse listConversations(ListConversationsRequest request) {
        return this.rawClient.listConversations(request).body();
    }

    /**
     * Returns a paginated list of conversations for the requesting agent, newest first.
     */
    public ListConversationsResponse listConversations(
            ListConversationsRequest request, RequestOptions requestOptions) {
        return this.rawClient.listConversations(request, requestOptions).body();
    }

    /**
     * Returns a single conversation by internal UUID or team-scoped external id.
     */
    public GetConversationResponse getConversation(String id) {
        return this.rawClient.getConversation(id).body();
    }

    /**
     * Returns a single conversation by internal UUID or team-scoped external id.
     */
    public GetConversationResponse getConversation(String id, RequestOptions requestOptions) {
        return this.rawClient.getConversation(id, requestOptions).body();
    }

    /**
     * Returns a single conversation by internal UUID or team-scoped external id.
     */
    public GetConversationResponse getConversation(String id, GetConversationRequest request) {
        return this.rawClient.getConversation(id, request).body();
    }

    /**
     * Returns a single conversation by internal UUID or team-scoped external id.
     */
    public GetConversationResponse getConversation(
            String id, GetConversationRequest request, RequestOptions requestOptions) {
        return this.rawClient.getConversation(id, request, requestOptions).body();
    }

    /**
     * Pauses the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public PauseConversationResponse pauseConversation(String id) {
        return this.rawClient.pauseConversation(id).body();
    }

    /**
     * Pauses the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public PauseConversationResponse pauseConversation(String id, RequestOptions requestOptions) {
        return this.rawClient.pauseConversation(id, requestOptions).body();
    }

    /**
     * Pauses the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public PauseConversationResponse pauseConversation(String id, PauseConversationRequest request) {
        return this.rawClient.pauseConversation(id, request).body();
    }

    /**
     * Pauses the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public PauseConversationResponse pauseConversation(
            String id, PauseConversationRequest request, RequestOptions requestOptions) {
        return this.rawClient.pauseConversation(id, request, requestOptions).body();
    }

    /**
     * Resumes the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public ResumeConversationResponse resumeConversation(String id) {
        return this.rawClient.resumeConversation(id).body();
    }

    /**
     * Resumes the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public ResumeConversationResponse resumeConversation(String id, RequestOptions requestOptions) {
        return this.rawClient.resumeConversation(id, requestOptions).body();
    }

    /**
     * Resumes the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public ResumeConversationResponse resumeConversation(String id, ResumeConversationRequest request) {
        return this.rawClient.resumeConversation(id, request).body();
    }

    /**
     * Resumes the agent on a conversation identified by internal UUID or team-scoped external id. Requires an API key.
     */
    public ResumeConversationResponse resumeConversation(
            String id, ResumeConversationRequest request, RequestOptions requestOptions) {
        return this.rawClient.resumeConversation(id, request, requestOptions).body();
    }
}
